# coding: utf-8

"""
    College Football Data API

    Build college football applications, models, and analysis with game, team, player, recruiting, ranking, and advanced metrics data. Request an API key at CollegeFootballData.com.

    The version of the OpenAPI document: 5.26.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cfbd.models.team_rushing_season import TeamRushingSeason  # noqa: E501

class TestTeamRushingSeason(unittest.TestCase):
    """TeamRushingSeason unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamRushingSeason:
        """Test TeamRushingSeason
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamRushingSeason`
        """
        model = TeamRushingSeason()  # noqa: E501
        if include_optional:
            return TeamRushingSeason(
                season = 56,
                team = '',
                conference = '',
                offense = cfbd.models.team_rushing_production.TeamRushingProduction(
                    attempts = 56, 
                    rushing_yards_available = 56, 
                    total_rushing_yards = 56, 
                    yards_per_carry = 1.337, 
                    individual_attempts = 56, 
                    unattributed_attempts = 56, 
                    sacks = 56, 
                    kneels = 56, 
                    team_rushes = 56, 
                    multi_carrier_attempts = 56, 
                    direction_eligible_attempts = 56, 
                    direction_available_attempts = 56, 
                    success_rate = 1.337, 
                    ppa = 1.337, 
                    total_ppa = 1.337, 
                    line_yards = 1.337, 
                    line_yards_total = 1.337, 
                    second_level_yards = 1.337, 
                    second_level_yards_total = 1.337, 
                    open_field_yards = 1.337, 
                    open_field_yards_total = 1.337, 
                    stuff_rate = 1.337, 
                    power_success = 1.337, 
                    explosiveness = 1.337, 
                    directions = cfbd.models.player_rushing_season_directions.PlayerRushingSeason_directions(
                        unknown = cfbd.models.rushing_direction_production.RushingDirectionProduction(
                            carries = 56, 
                            yards = 56, 
                            yards_per_carry = 1.337, 
                            success_rate = 1.337, 
                            ppa = 1.337, 
                            total_ppa = 1.337, 
                            line_yards = 1.337, 
                            line_yards_total = 1.337, 
                            second_level_yards = 1.337, 
                            second_level_yards_total = 1.337, 
                            open_field_yards = 1.337, 
                            open_field_yards_total = 1.337, 
                            stuff_rate = 1.337, 
                            power_success = 1.337, 
                            explosiveness = 1.337, ), 
                        right = cfbd.models.rushing_direction_production.RushingDirectionProduction(
                            carries = 56, 
                            yards = 56, 
                            yards_per_carry = 1.337, 
                            success_rate = 1.337, 
                            ppa = 1.337, 
                            total_ppa = 1.337, 
                            line_yards = 1.337, 
                            line_yards_total = 1.337, 
                            second_level_yards = 1.337, 
                            second_level_yards_total = 1.337, 
                            open_field_yards = 1.337, 
                            open_field_yards_total = 1.337, 
                            stuff_rate = 1.337, 
                            power_success = 1.337, 
                            explosiveness = 1.337, ), 
                        middle = , 
                        left = , ), 
                    touchdown_status_available = 56, 
                    rushing_touchdowns = 56, ),
                defense = cfbd.models.team_rushing_production.TeamRushingProduction(
                    attempts = 56, 
                    rushing_yards_available = 56, 
                    total_rushing_yards = 56, 
                    yards_per_carry = 1.337, 
                    individual_attempts = 56, 
                    unattributed_attempts = 56, 
                    sacks = 56, 
                    kneels = 56, 
                    team_rushes = 56, 
                    multi_carrier_attempts = 56, 
                    direction_eligible_attempts = 56, 
                    direction_available_attempts = 56, 
                    success_rate = 1.337, 
                    ppa = 1.337, 
                    total_ppa = 1.337, 
                    line_yards = 1.337, 
                    line_yards_total = 1.337, 
                    second_level_yards = 1.337, 
                    second_level_yards_total = 1.337, 
                    open_field_yards = 1.337, 
                    open_field_yards_total = 1.337, 
                    stuff_rate = 1.337, 
                    power_success = 1.337, 
                    explosiveness = 1.337, 
                    directions = cfbd.models.player_rushing_season_directions.PlayerRushingSeason_directions(
                        unknown = cfbd.models.rushing_direction_production.RushingDirectionProduction(
                            carries = 56, 
                            yards = 56, 
                            yards_per_carry = 1.337, 
                            success_rate = 1.337, 
                            ppa = 1.337, 
                            total_ppa = 1.337, 
                            line_yards = 1.337, 
                            line_yards_total = 1.337, 
                            second_level_yards = 1.337, 
                            second_level_yards_total = 1.337, 
                            open_field_yards = 1.337, 
                            open_field_yards_total = 1.337, 
                            stuff_rate = 1.337, 
                            power_success = 1.337, 
                            explosiveness = 1.337, ), 
                        right = cfbd.models.rushing_direction_production.RushingDirectionProduction(
                            carries = 56, 
                            yards = 56, 
                            yards_per_carry = 1.337, 
                            success_rate = 1.337, 
                            ppa = 1.337, 
                            total_ppa = 1.337, 
                            line_yards = 1.337, 
                            line_yards_total = 1.337, 
                            second_level_yards = 1.337, 
                            second_level_yards_total = 1.337, 
                            open_field_yards = 1.337, 
                            open_field_yards_total = 1.337, 
                            stuff_rate = 1.337, 
                            power_success = 1.337, 
                            explosiveness = 1.337, ), 
                        middle = , 
                        left = , ), 
                    touchdown_status_available = 56, 
                    rushing_touchdowns = 56, )
            )
        else:
            return TeamRushingSeason(
                season = 56,
                team = '',
                conference = '',
                offense = cfbd.models.team_rushing_production.TeamRushingProduction(
                    attempts = 56, 
                    rushing_yards_available = 56, 
                    total_rushing_yards = 56, 
                    yards_per_carry = 1.337, 
                    individual_attempts = 56, 
                    unattributed_attempts = 56, 
                    sacks = 56, 
                    kneels = 56, 
                    team_rushes = 56, 
                    multi_carrier_attempts = 56, 
                    direction_eligible_attempts = 56, 
                    direction_available_attempts = 56, 
                    success_rate = 1.337, 
                    ppa = 1.337, 
                    total_ppa = 1.337, 
                    line_yards = 1.337, 
                    line_yards_total = 1.337, 
                    second_level_yards = 1.337, 
                    second_level_yards_total = 1.337, 
                    open_field_yards = 1.337, 
                    open_field_yards_total = 1.337, 
                    stuff_rate = 1.337, 
                    power_success = 1.337, 
                    explosiveness = 1.337, 
                    directions = cfbd.models.player_rushing_season_directions.PlayerRushingSeason_directions(
                        unknown = cfbd.models.rushing_direction_production.RushingDirectionProduction(
                            carries = 56, 
                            yards = 56, 
                            yards_per_carry = 1.337, 
                            success_rate = 1.337, 
                            ppa = 1.337, 
                            total_ppa = 1.337, 
                            line_yards = 1.337, 
                            line_yards_total = 1.337, 
                            second_level_yards = 1.337, 
                            second_level_yards_total = 1.337, 
                            open_field_yards = 1.337, 
                            open_field_yards_total = 1.337, 
                            stuff_rate = 1.337, 
                            power_success = 1.337, 
                            explosiveness = 1.337, ), 
                        right = cfbd.models.rushing_direction_production.RushingDirectionProduction(
                            carries = 56, 
                            yards = 56, 
                            yards_per_carry = 1.337, 
                            success_rate = 1.337, 
                            ppa = 1.337, 
                            total_ppa = 1.337, 
                            line_yards = 1.337, 
                            line_yards_total = 1.337, 
                            second_level_yards = 1.337, 
                            second_level_yards_total = 1.337, 
                            open_field_yards = 1.337, 
                            open_field_yards_total = 1.337, 
                            stuff_rate = 1.337, 
                            power_success = 1.337, 
                            explosiveness = 1.337, ), 
                        middle = , 
                        left = , ), 
                    touchdown_status_available = 56, 
                    rushing_touchdowns = 56, ),
                defense = cfbd.models.team_rushing_production.TeamRushingProduction(
                    attempts = 56, 
                    rushing_yards_available = 56, 
                    total_rushing_yards = 56, 
                    yards_per_carry = 1.337, 
                    individual_attempts = 56, 
                    unattributed_attempts = 56, 
                    sacks = 56, 
                    kneels = 56, 
                    team_rushes = 56, 
                    multi_carrier_attempts = 56, 
                    direction_eligible_attempts = 56, 
                    direction_available_attempts = 56, 
                    success_rate = 1.337, 
                    ppa = 1.337, 
                    total_ppa = 1.337, 
                    line_yards = 1.337, 
                    line_yards_total = 1.337, 
                    second_level_yards = 1.337, 
                    second_level_yards_total = 1.337, 
                    open_field_yards = 1.337, 
                    open_field_yards_total = 1.337, 
                    stuff_rate = 1.337, 
                    power_success = 1.337, 
                    explosiveness = 1.337, 
                    directions = cfbd.models.player_rushing_season_directions.PlayerRushingSeason_directions(
                        unknown = cfbd.models.rushing_direction_production.RushingDirectionProduction(
                            carries = 56, 
                            yards = 56, 
                            yards_per_carry = 1.337, 
                            success_rate = 1.337, 
                            ppa = 1.337, 
                            total_ppa = 1.337, 
                            line_yards = 1.337, 
                            line_yards_total = 1.337, 
                            second_level_yards = 1.337, 
                            second_level_yards_total = 1.337, 
                            open_field_yards = 1.337, 
                            open_field_yards_total = 1.337, 
                            stuff_rate = 1.337, 
                            power_success = 1.337, 
                            explosiveness = 1.337, ), 
                        right = cfbd.models.rushing_direction_production.RushingDirectionProduction(
                            carries = 56, 
                            yards = 56, 
                            yards_per_carry = 1.337, 
                            success_rate = 1.337, 
                            ppa = 1.337, 
                            total_ppa = 1.337, 
                            line_yards = 1.337, 
                            line_yards_total = 1.337, 
                            second_level_yards = 1.337, 
                            second_level_yards_total = 1.337, 
                            open_field_yards = 1.337, 
                            open_field_yards_total = 1.337, 
                            stuff_rate = 1.337, 
                            power_success = 1.337, 
                            explosiveness = 1.337, ), 
                        middle = , 
                        left = , ), 
                    touchdown_status_available = 56, 
                    rushing_touchdowns = 56, ),
        )
        """

    def testTeamRushingSeason(self):
        """Test TeamRushingSeason"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
