# coding: utf-8

"""
    College Football Data API

    Build college football applications, models, and analysis with game, team, player, recruiting, ranking, and advanced metrics data. Request an API key at CollegeFootballData.com.

    The version of the OpenAPI document: 5.26.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cfbd.models.ranking_poll import RankingPoll  # noqa: E501

class TestRankingPoll(unittest.TestCase):
    """RankingPoll unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRankingPoll(self):
        """Test RankingPoll"""
        # inst = RankingPoll()

if __name__ == '__main__':
    unittest.main()
