# coding: utf-8

"""
    College Football Data API

    This is an API for query various college football datasets and analytics. API keys can be acquired from the CollegeFootballData.com website.

    The version of the OpenAPI document: 5.20.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cfbd.models.user_feature_access import UserFeatureAccess  # noqa: E501

class TestUserFeatureAccess(unittest.TestCase):
    """UserFeatureAccess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserFeatureAccess:
        """Test UserFeatureAccess
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserFeatureAccess`
        """
        model = UserFeatureAccess()  # noqa: E501
        if include_optional:
            return UserFeatureAccess(
                adjusted_metrics = True,
                weather = True,
                scoreboard = True,
                live_play_by_play = True,
                graph_ql = True
            )
        else:
            return UserFeatureAccess(
                adjusted_metrics = True,
                weather = True,
                scoreboard = True,
                live_play_by_play = True,
                graph_ql = True,
        )
        """

    def testUserFeatureAccess(self):
        """Test UserFeatureAccess"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
