# coding: utf-8

"""
    College Football Data API

    Build college football applications, models, and analysis with game, team, player, recruiting, ranking, and advanced metrics data. Request an API key at CollegeFootballData.com.

    The version of the OpenAPI document: 5.26.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cfbd.models.coach_record_splits import CoachRecordSplits  # noqa: E501

class TestCoachRecordSplits(unittest.TestCase):
    """CoachRecordSplits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoachRecordSplits:
        """Test CoachRecordSplits
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CoachRecordSplits`
        """
        model = CoachRecordSplits()  # noqa: E501
        if include_optional:
            return CoachRecordSplits(
                conference = cfbd.models.coach_record.CoachRecord(
                    games = 56, 
                    wins = 56, 
                    losses = 56, 
                    ties = 56, 
                    win_percentage = 1.337, ),
                postseason = cfbd.models.coach_record.CoachRecord(
                    games = 56, 
                    wins = 56, 
                    losses = 56, 
                    ties = 56, 
                    win_percentage = 1.337, ),
                home = cfbd.models.coach_record.CoachRecord(
                    games = 56, 
                    wins = 56, 
                    losses = 56, 
                    ties = 56, 
                    win_percentage = 1.337, ),
                away = cfbd.models.coach_record.CoachRecord(
                    games = 56, 
                    wins = 56, 
                    losses = 56, 
                    ties = 56, 
                    win_percentage = 1.337, ),
                neutral = cfbd.models.coach_record.CoachRecord(
                    games = 56, 
                    wins = 56, 
                    losses = 56, 
                    ties = 56, 
                    win_percentage = 1.337, )
            )
        else:
            return CoachRecordSplits(
                conference = cfbd.models.coach_record.CoachRecord(
                    games = 56, 
                    wins = 56, 
                    losses = 56, 
                    ties = 56, 
                    win_percentage = 1.337, ),
                postseason = cfbd.models.coach_record.CoachRecord(
                    games = 56, 
                    wins = 56, 
                    losses = 56, 
                    ties = 56, 
                    win_percentage = 1.337, ),
                home = cfbd.models.coach_record.CoachRecord(
                    games = 56, 
                    wins = 56, 
                    losses = 56, 
                    ties = 56, 
                    win_percentage = 1.337, ),
                away = cfbd.models.coach_record.CoachRecord(
                    games = 56, 
                    wins = 56, 
                    losses = 56, 
                    ties = 56, 
                    win_percentage = 1.337, ),
                neutral = cfbd.models.coach_record.CoachRecord(
                    games = 56, 
                    wins = 56, 
                    losses = 56, 
                    ties = 56, 
                    win_percentage = 1.337, ),
        )
        """

    def testCoachRecordSplits(self):
        """Test CoachRecordSplits"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
