# coding: utf-8

"""
    College Football Data API

    This is an API for query various college football datasets and analytics. API keys can be acquired from the CollegeFootballData.com website.

    The version of the OpenAPI document: 5.21.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cfbd.models.coach_career import CoachCareer  # noqa: E501

class TestCoachCareer(unittest.TestCase):
    """CoachCareer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoachCareer:
        """Test CoachCareer
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CoachCareer`
        """
        model = CoachCareer()  # noqa: E501
        if include_optional:
            return CoachCareer(
                games = 56,
                wins = 56,
                losses = 56,
                ties = 56,
                win_percentage = 1.337,
                seasons = 56,
                teams = 56,
                first_year = 56,
                last_year = 56
            )
        else:
            return CoachCareer(
                games = 56,
                wins = 56,
                losses = 56,
                ties = 56,
                win_percentage = 1.337,
                seasons = 56,
                teams = 56,
                first_year = 56,
                last_year = 56,
        )
        """

    def testCoachCareer(self):
        """Test CoachCareer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
