# coding: utf-8

"""
    College Football Data API

    Build college football applications, models, and analysis with game, team, player, recruiting, ranking, and advanced metrics data. Request an API key at CollegeFootballData.com.

    The version of the OpenAPI document: 5.26.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cfbd.models.coach_profile import CoachProfile  # noqa: E501

class TestCoachProfile(unittest.TestCase):
    """CoachProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoachProfile:
        """Test CoachProfile
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CoachProfile`
        """
        model = CoachProfile()  # noqa: E501
        if include_optional:
            return CoachProfile(
                id = 56,
                first_name = '',
                last_name = '',
                display_name = '',
                current_team = cfbd.models.coach_season_team_reference.CoachSeasonTeamReference(
                    id = 56, 
                    school = '', 
                    conference = '', ),
                career = cfbd.models.coach_career.CoachCareer(
                    games = 56, 
                    wins = 56, 
                    losses = 56, 
                    ties = 56, 
                    win_percentage = 1.337, 
                    seasons = 56, 
                    teams = 56, 
                    first_year = 56, 
                    last_year = 56, ),
                birth_date = '',
                alma_mater = cfbd.models.coach_alma_mater.CoachAlmaMater(
                    id = 56, 
                    school = '', ),
                graduation_year = 56,
                wikidata_id = '',
                hall_of_fame_year = 56
            )
        else:
            return CoachProfile(
                id = 56,
                first_name = '',
                last_name = '',
                display_name = '',
                current_team = cfbd.models.coach_season_team_reference.CoachSeasonTeamReference(
                    id = 56, 
                    school = '', 
                    conference = '', ),
                career = cfbd.models.coach_career.CoachCareer(
                    games = 56, 
                    wins = 56, 
                    losses = 56, 
                    ties = 56, 
                    win_percentage = 1.337, 
                    seasons = 56, 
                    teams = 56, 
                    first_year = 56, 
                    last_year = 56, ),
                birth_date = '',
                alma_mater = cfbd.models.coach_alma_mater.CoachAlmaMater(
                    id = 56, 
                    school = '', ),
                graduation_year = 56,
                wikidata_id = '',
                hall_of_fame_year = 56,
        )
        """

    def testCoachProfile(self):
        """Test CoachProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
