# coding: utf-8

"""
    College Football Data API

    This is an API for query various college football datasets and analytics. API keys can be acquired from the CollegeFootballData.com website.

    The version of the OpenAPI document: 5.13.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cfbd.models.game_havoc_stats import GameHavocStats  # noqa: E501

class TestGameHavocStats(unittest.TestCase):
    """GameHavocStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameHavocStats:
        """Test GameHavocStats
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameHavocStats`
        """
        model = GameHavocStats()  # noqa: E501
        if include_optional:
            return GameHavocStats(
                game_id = 56,
                season = 56,
                season_type = 'allstar',
                week = 56,
                team = '',
                conference = '',
                opponent = '',
                opponent_conference = '',
                offense = cfbd.models.game_havoc_stats_offense.GameHavocStats_offense(
                    db_havoc_rate = 1.337, 
                    front_seven_havoc_rate = 1.337, 
                    havoc_rate = 1.337, 
                    db_havoc_events = 1.337, 
                    front_seven_havoc_events = 1.337, 
                    total_havoc_events = 1.337, 
                    total_plays = 1.337, ),
                defense = cfbd.models.game_havoc_stats_offense.GameHavocStats_offense(
                    db_havoc_rate = 1.337, 
                    front_seven_havoc_rate = 1.337, 
                    havoc_rate = 1.337, 
                    db_havoc_events = 1.337, 
                    front_seven_havoc_events = 1.337, 
                    total_havoc_events = 1.337, 
                    total_plays = 1.337, )
            )
        else:
            return GameHavocStats(
                game_id = 56,
                season = 56,
                season_type = 'allstar',
                week = 56,
                team = '',
                conference = '',
                opponent = '',
                opponent_conference = '',
                offense = cfbd.models.game_havoc_stats_offense.GameHavocStats_offense(
                    db_havoc_rate = 1.337, 
                    front_seven_havoc_rate = 1.337, 
                    havoc_rate = 1.337, 
                    db_havoc_events = 1.337, 
                    front_seven_havoc_events = 1.337, 
                    total_havoc_events = 1.337, 
                    total_plays = 1.337, ),
                defense = cfbd.models.game_havoc_stats_offense.GameHavocStats_offense(
                    db_havoc_rate = 1.337, 
                    front_seven_havoc_rate = 1.337, 
                    havoc_rate = 1.337, 
                    db_havoc_events = 1.337, 
                    front_seven_havoc_events = 1.337, 
                    total_havoc_events = 1.337, 
                    total_plays = 1.337, ),
        )
        """

    def testGameHavocStats(self):
        """Test GameHavocStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
