# coding: utf-8

"""
    College Football Data API

    Build college football applications, models, and analysis with game, team, player, recruiting, ranking, and advanced metrics data. Request an API key at CollegeFootballData.com.

    The version of the OpenAPI document: 5.26.2
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cfbd.models.rush_attribution_status import RushAttributionStatus  # noqa: E501

class TestRushAttributionStatus(unittest.TestCase):
    """RushAttributionStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRushAttributionStatus(self):
        """Test RushAttributionStatus"""
        # inst = RushAttributionStatus()

if __name__ == '__main__':
    unittest.main()
