# coding: utf-8

"""
    College Football Data API

    This is an API for query various college football datasets and analytics. API keys can be acquired from the CollegeFootballData.com website.

    The version of the OpenAPI document: 5.7.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cfbd.api.drives_api import DrivesApi  # noqa: E501


class TestDrivesApi(unittest.TestCase):
    """DrivesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DrivesApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_get_drives(self) -> None:
        """Test case for get_drives

        """
        pass


if __name__ == '__main__':
    unittest.main()
