# coding: utf-8

"""
    College Football Data API

    Build college football applications, models, and analysis with game, team, player, recruiting, ranking, and advanced metrics data. Request an API key at CollegeFootballData.com.

    The version of the OpenAPI document: 5.31.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cfbd.models.preview_section_preview_player_wepa_array import PreviewSectionPreviewPlayerWepaArray  # noqa: E501

class TestPreviewSectionPreviewPlayerWepaArray(unittest.TestCase):
    """PreviewSectionPreviewPlayerWepaArray unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PreviewSectionPreviewPlayerWepaArray:
        """Test PreviewSectionPreviewPlayerWepaArray
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PreviewSectionPreviewPlayerWepaArray`
        """
        model = PreviewSectionPreviewPlayerWepaArray()  # noqa: E501
        if include_optional:
            return PreviewSectionPreviewPlayerWepaArray(
                status = 'available',
                reason = 'no_data',
                assembled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                source_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                data = [
                    cfbd.models.preview_player_wepa.PreviewPlayerWepa(
                        team = '', 
                        year = 56, 
                        athlete_id = '', 
                        athlete_name = '', 
                        position = '', 
                        conference = '', 
                        wepa = 1.337, 
                        plays = 56, )
                    ]
            )
        else:
            return PreviewSectionPreviewPlayerWepaArray(
                status = 'available',
                reason = 'no_data',
                assembled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                source_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                data = [
                    cfbd.models.preview_player_wepa.PreviewPlayerWepa(
                        team = '', 
                        year = 56, 
                        athlete_id = '', 
                        athlete_name = '', 
                        position = '', 
                        conference = '', 
                        wepa = 1.337, 
                        plays = 56, )
                    ],
        )
        """

    def testPreviewSectionPreviewPlayerWepaArray(self):
        """Test PreviewSectionPreviewPlayerWepaArray"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
