# coding: utf-8

"""
    College Football Data API

    Build college football applications, models, and analysis with game, team, player, recruiting, ranking, and advanced metrics data. Request an API key at CollegeFootballData.com.

    The version of the OpenAPI document: 5.22.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cfbd.models.coach_not_found import CoachNotFound  # noqa: E501

class TestCoachNotFound(unittest.TestCase):
    """CoachNotFound unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoachNotFound:
        """Test CoachNotFound
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CoachNotFound`
        """
        model = CoachNotFound()  # noqa: E501
        if include_optional:
            return CoachNotFound(
                message = 'Coach not found'
            )
        else:
            return CoachNotFound(
                message = 'Coach not found',
        )
        """

    def testCoachNotFound(self):
        """Test CoachNotFound"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
