# coding: utf-8

"""
    College Football Data API

    This is an API for query various college football datasets and analytics. API keys can be acquired from the CollegeFootballData.com website.

    The version of the OpenAPI document: 5.21.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cfbd.models.cfp_coach_season_outcome import CfpCoachSeasonOutcome  # noqa: E501

class TestCfpCoachSeasonOutcome(unittest.TestCase):
    """CfpCoachSeasonOutcome unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCfpCoachSeasonOutcome(self):
        """Test CfpCoachSeasonOutcome"""
        # inst = CfpCoachSeasonOutcome()

if __name__ == '__main__':
    unittest.main()
