# coding: utf-8

"""
    College Football Data API

    Build college football applications, models, and analysis with game, team, player, recruiting, ranking, and advanced metrics data. Request an API key at CollegeFootballData.com.

    The version of the OpenAPI document: 5.31.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cfbd.models.series_meeting import SeriesMeeting  # noqa: E501

class TestSeriesMeeting(unittest.TestCase):
    """SeriesMeeting unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SeriesMeeting:
        """Test SeriesMeeting
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SeriesMeeting`
        """
        model = SeriesMeeting()  # noqa: E501
        if include_optional:
            return SeriesMeeting(
                game_id = 56,
                season = 56,
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                home_team_id = 56,
                home_team = '',
                away_team_id = 56,
                away_team = '',
                neutral_site = True,
                venue = cfbd.models.preview_venue.PreviewVenue(
                    id = 56, 
                    name = '', 
                    city = '', 
                    state = '', ),
                home_points = 56,
                away_points = 56,
                winner_team_id = 56,
                result = 'win'
            )
        else:
            return SeriesMeeting(
                game_id = 56,
                season = 56,
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                home_team_id = 56,
                home_team = '',
                away_team_id = 56,
                away_team = '',
                neutral_site = True,
                venue = cfbd.models.preview_venue.PreviewVenue(
                    id = 56, 
                    name = '', 
                    city = '', 
                    state = '', ),
                home_points = 56,
                away_points = 56,
                winner_team_id = 56,
                result = 'win',
        )
        """

    def testSeriesMeeting(self):
        """Test SeriesMeeting"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
