# coding: utf-8

"""
    College Football Data API

    Build college football applications, models, and analysis with game, team, player, recruiting, ranking, and advanced metrics data. Request an API key at CollegeFootballData.com.

    The version of the OpenAPI document: 5.31.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cfbd.models.game_preview_metadata import GamePreviewMetadata  # noqa: E501

class TestGamePreviewMetadata(unittest.TestCase):
    """GamePreviewMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GamePreviewMetadata:
        """Test GamePreviewMetadata
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GamePreviewMetadata`
        """
        model = GamePreviewMetadata()  # noqa: E501
        if include_optional:
            return GamePreviewMetadata(
                id = 56,
                season = 56,
                week = 56,
                season_type = None,
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                start_time_tbd = True,
                status = 'scheduled',
                status_checked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                neutral_site = True,
                conference_game = True,
                venue = cfbd.models.preview_venue.PreviewVenue(
                    id = 56, 
                    name = '', 
                    city = '', 
                    state = '', ),
                home_team = cfbd.models.preview_team_identity.PreviewTeamIdentity(
                    id = 56, 
                    name = '', 
                    conference = '', 
                    conference_abbreviation = '', 
                    classification = null, 
                    points = 56, ),
                away_team = cfbd.models.preview_team_identity.PreviewTeamIdentity(
                    id = 56, 
                    name = '', 
                    conference = '', 
                    conference_abbreviation = '', 
                    classification = null, 
                    points = 56, ),
                playoff = cfbd.models.game_playoff.GamePlayoff(
                    competition = 'cfp', 
                    format = '', 
                    round = 'first_round', 
                    round_name = '', 
                    bracket_slot = '', 
                    home_seed = 56, 
                    away_seed = 56, 
                    bowl_name = '', )
            )
        else:
            return GamePreviewMetadata(
                id = 56,
                season = 56,
                week = 56,
                season_type = None,
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                start_time_tbd = True,
                status = 'scheduled',
                status_checked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                neutral_site = True,
                conference_game = True,
                venue = cfbd.models.preview_venue.PreviewVenue(
                    id = 56, 
                    name = '', 
                    city = '', 
                    state = '', ),
                home_team = cfbd.models.preview_team_identity.PreviewTeamIdentity(
                    id = 56, 
                    name = '', 
                    conference = '', 
                    conference_abbreviation = '', 
                    classification = null, 
                    points = 56, ),
                away_team = cfbd.models.preview_team_identity.PreviewTeamIdentity(
                    id = 56, 
                    name = '', 
                    conference = '', 
                    conference_abbreviation = '', 
                    classification = null, 
                    points = 56, ),
                playoff = cfbd.models.game_playoff.GamePlayoff(
                    competition = 'cfp', 
                    format = '', 
                    round = 'first_round', 
                    round_name = '', 
                    bracket_slot = '', 
                    home_seed = 56, 
                    away_seed = 56, 
                    bowl_name = '', ),
        )
        """

    def testGamePreviewMetadata(self):
        """Test GamePreviewMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
