# coding: utf-8

"""
    College Football Data API

    Build college football applications, models, and analysis with game, team, player, recruiting, ranking, and advanced metrics data. Request an API key at CollegeFootballData.com.

    The version of the OpenAPI document: 5.26.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cfbd.models.coach_alma_mater import CoachAlmaMater  # noqa: E501

class TestCoachAlmaMater(unittest.TestCase):
    """CoachAlmaMater unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoachAlmaMater:
        """Test CoachAlmaMater
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CoachAlmaMater`
        """
        model = CoachAlmaMater()  # noqa: E501
        if include_optional:
            return CoachAlmaMater(
                id = 56,
                school = ''
            )
        else:
            return CoachAlmaMater(
                id = 56,
                school = '',
        )
        """

    def testCoachAlmaMater(self):
        """Test CoachAlmaMater"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
