# coding: utf-8

"""
    College Football Data API

    Build college football applications, models, and analysis with game, team, player, recruiting, ranking, and advanced metrics data. Request an API key at CollegeFootballData.com.

    The version of the OpenAPI document: 5.30.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cfbd.models.advanced_box_score_players import AdvancedBoxScorePlayers  # noqa: E501

class TestAdvancedBoxScorePlayers(unittest.TestCase):
    """AdvancedBoxScorePlayers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvancedBoxScorePlayers:
        """Test AdvancedBoxScorePlayers
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvancedBoxScorePlayers`
        """
        model = AdvancedBoxScorePlayers()  # noqa: E501
        if include_optional:
            return AdvancedBoxScorePlayers(
                ppa = [
                    cfbd.models.player_ppa.PlayerPPA(
                        player = '', 
                        team = '', 
                        position = '', 
                        average = cfbd.models.player_stats_by_quarter.PlayerStatsByQuarter(
                            total = 1.337, 
                            quarter1 = 1.337, 
                            quarter2 = 1.337, 
                            quarter3 = 1.337, 
                            quarter4 = 1.337, 
                            rushing = 1.337, 
                            passing = 1.337, ), 
                        cumulative = cfbd.models.player_stats_by_quarter.PlayerStatsByQuarter(
                            total = 1.337, 
                            quarter1 = 1.337, 
                            quarter2 = 1.337, 
                            quarter3 = 1.337, 
                            quarter4 = 1.337, 
                            rushing = 1.337, 
                            passing = 1.337, ), )
                    ],
                usage = [
                    cfbd.models.player_game_usage.PlayerGameUsage(
                        total = 1.337, 
                        quarter1 = 1.337, 
                        quarter2 = 1.337, 
                        quarter3 = 1.337, 
                        quarter4 = 1.337, 
                        rushing = 1.337, 
                        passing = 1.337, 
                        player = '', 
                        team = '', 
                        position = '', )
                    ],
                rushing = [
                    cfbd.models.player_rushing_game.PlayerRushingGame(
                        attempts = 56, 
                        rushing_yards_available = 56, 
                        total_rushing_yards = 56, 
                        yards_per_carry = 1.337, 
                        individual_attempts = 56, 
                        unattributed_attempts = 56, 
                        sacks = 56, 
                        kneels = 56, 
                        team_rushes = 56, 
                        multi_carrier_attempts = 56, 
                        direction_eligible_attempts = 56, 
                        direction_available_attempts = 56, 
                        success_rate = 1.337, 
                        ppa = 1.337, 
                        total_ppa = 1.337, 
                        line_yards = 1.337, 
                        line_yards_total = 1.337, 
                        second_level_yards = 1.337, 
                        second_level_yards_total = 1.337, 
                        open_field_yards = 1.337, 
                        open_field_yards_total = 1.337, 
                        stuff_rate = 1.337, 
                        power_success = 1.337, 
                        explosiveness = 1.337, 
                        directions = cfbd.models.team_rushing_production_directions.TeamRushingProduction_directions(
                            unknown = cfbd.models.rushing_direction_production.RushingDirectionProduction(
                                carries = 56, 
                                yards = 56, 
                                yards_per_carry = 1.337, 
                                success_rate = 1.337, 
                                ppa = 1.337, 
                                total_ppa = 1.337, 
                                line_yards = 1.337, 
                                line_yards_total = 1.337, 
                                second_level_yards = 1.337, 
                                second_level_yards_total = 1.337, 
                                open_field_yards = 1.337, 
                                open_field_yards_total = 1.337, 
                                stuff_rate = 1.337, 
                                power_success = 1.337, 
                                explosiveness = 1.337, ), 
                            right = cfbd.models.rushing_direction_production.RushingDirectionProduction(
                                carries = 56, 
                                yards = 56, 
                                yards_per_carry = 1.337, 
                                success_rate = 1.337, 
                                ppa = 1.337, 
                                total_ppa = 1.337, 
                                line_yards = 1.337, 
                                line_yards_total = 1.337, 
                                second_level_yards = 1.337, 
                                second_level_yards_total = 1.337, 
                                open_field_yards = 1.337, 
                                open_field_yards_total = 1.337, 
                                stuff_rate = 1.337, 
                                power_success = 1.337, 
                                explosiveness = 1.337, ), 
                            middle = , 
                            left = , ), 
                        game_id = 56, 
                        season = 56, 
                        week = 56, 
                        season_type = 'regular', 
                        player_id = '', 
                        player = '', 
                        team = '', 
                        conference = '', 
                        opponent = '', )
                    ],
                passing = [
                    cfbd.models.player_passing_game.PlayerPassingGame(
                        attempts = 56, 
                        completions = 56, 
                        incompletions = 56, 
                        interceptions = 56, 
                        completion_rate = 1.337, 
                        air_yards_attempts_available = 56, 
                        total_air_yards = 56, 
                        average_depth_of_target = 1.337, 
                        total_yards_attempts_available = 56, 
                        total_yards = 56, 
                        yards_after_catch_attempts_available = 56, 
                        total_yards_after_catch = 56, 
                        average_yards_after_catch = 1.337, 
                        success_rate = 1.337, 
                        ppa = 1.337, 
                        total_ppa = 1.337, 
                        explosiveness = 1.337, 
                        ppa_attempts_available = 56, 
                        success_attempts_available = 56, 
                        successful_attempts = 56, 
                        successful_ppa_attempts_available = 56, 
                        location_eligible_attempts = 56, 
                        location_available_attempts = 56, 
                        locations = cfbd.models.passing_locations.PassingLocations(
                            short_left = cfbd.models.passing_location_production.PassingLocationProduction(
                                attempts = 56, 
                                completions = 56, 
                                incompletions = 56, 
                                interceptions = 56, 
                                completion_rate = 1.337, 
                                air_yards_attempts_available = 56, 
                                total_air_yards = 56, 
                                average_depth_of_target = 1.337, 
                                total_yards_attempts_available = 56, 
                                total_yards = 56, 
                                yards_after_catch_attempts_available = 56, 
                                total_yards_after_catch = 56, 
                                average_yards_after_catch = 1.337, 
                                success_rate = 1.337, 
                                ppa = 1.337, 
                                total_ppa = 1.337, 
                                explosiveness = 1.337, 
                                ppa_attempts_available = 56, 
                                success_attempts_available = 56, 
                                successful_attempts = 56, 
                                successful_ppa_attempts_available = 56, 
                                yards_per_attempt = 1.337, 
                                air_yards_per_attempt = 1.337, ), 
                            short_middle = cfbd.models.passing_location_production.PassingLocationProduction(
                                attempts = 56, 
                                completions = 56, 
                                incompletions = 56, 
                                interceptions = 56, 
                                completion_rate = 1.337, 
                                air_yards_attempts_available = 56, 
                                total_air_yards = 56, 
                                average_depth_of_target = 1.337, 
                                total_yards_attempts_available = 56, 
                                total_yards = 56, 
                                yards_after_catch_attempts_available = 56, 
                                total_yards_after_catch = 56, 
                                average_yards_after_catch = 1.337, 
                                success_rate = 1.337, 
                                ppa = 1.337, 
                                total_ppa = 1.337, 
                                explosiveness = 1.337, 
                                ppa_attempts_available = 56, 
                                success_attempts_available = 56, 
                                successful_attempts = 56, 
                                successful_ppa_attempts_available = 56, 
                                yards_per_attempt = 1.337, 
                                air_yards_per_attempt = 1.337, ), 
                            short_right = , 
                            deep_left = , 
                            deep_middle = , 
                            deep_right = , 
                            unknown = , ), 
                        game_id = 56, 
                        season = 56, 
                        week = 56, 
                        season_type = 'regular', 
                        player_id = '', 
                        player = '', 
                        team = '', 
                        conference = '', 
                        opponent = '', )
                    ]
            )
        else:
            return AdvancedBoxScorePlayers(
                ppa = [
                    cfbd.models.player_ppa.PlayerPPA(
                        player = '', 
                        team = '', 
                        position = '', 
                        average = cfbd.models.player_stats_by_quarter.PlayerStatsByQuarter(
                            total = 1.337, 
                            quarter1 = 1.337, 
                            quarter2 = 1.337, 
                            quarter3 = 1.337, 
                            quarter4 = 1.337, 
                            rushing = 1.337, 
                            passing = 1.337, ), 
                        cumulative = cfbd.models.player_stats_by_quarter.PlayerStatsByQuarter(
                            total = 1.337, 
                            quarter1 = 1.337, 
                            quarter2 = 1.337, 
                            quarter3 = 1.337, 
                            quarter4 = 1.337, 
                            rushing = 1.337, 
                            passing = 1.337, ), )
                    ],
                usage = [
                    cfbd.models.player_game_usage.PlayerGameUsage(
                        total = 1.337, 
                        quarter1 = 1.337, 
                        quarter2 = 1.337, 
                        quarter3 = 1.337, 
                        quarter4 = 1.337, 
                        rushing = 1.337, 
                        passing = 1.337, 
                        player = '', 
                        team = '', 
                        position = '', )
                    ],
                rushing = [
                    cfbd.models.player_rushing_game.PlayerRushingGame(
                        attempts = 56, 
                        rushing_yards_available = 56, 
                        total_rushing_yards = 56, 
                        yards_per_carry = 1.337, 
                        individual_attempts = 56, 
                        unattributed_attempts = 56, 
                        sacks = 56, 
                        kneels = 56, 
                        team_rushes = 56, 
                        multi_carrier_attempts = 56, 
                        direction_eligible_attempts = 56, 
                        direction_available_attempts = 56, 
                        success_rate = 1.337, 
                        ppa = 1.337, 
                        total_ppa = 1.337, 
                        line_yards = 1.337, 
                        line_yards_total = 1.337, 
                        second_level_yards = 1.337, 
                        second_level_yards_total = 1.337, 
                        open_field_yards = 1.337, 
                        open_field_yards_total = 1.337, 
                        stuff_rate = 1.337, 
                        power_success = 1.337, 
                        explosiveness = 1.337, 
                        directions = cfbd.models.team_rushing_production_directions.TeamRushingProduction_directions(
                            unknown = cfbd.models.rushing_direction_production.RushingDirectionProduction(
                                carries = 56, 
                                yards = 56, 
                                yards_per_carry = 1.337, 
                                success_rate = 1.337, 
                                ppa = 1.337, 
                                total_ppa = 1.337, 
                                line_yards = 1.337, 
                                line_yards_total = 1.337, 
                                second_level_yards = 1.337, 
                                second_level_yards_total = 1.337, 
                                open_field_yards = 1.337, 
                                open_field_yards_total = 1.337, 
                                stuff_rate = 1.337, 
                                power_success = 1.337, 
                                explosiveness = 1.337, ), 
                            right = cfbd.models.rushing_direction_production.RushingDirectionProduction(
                                carries = 56, 
                                yards = 56, 
                                yards_per_carry = 1.337, 
                                success_rate = 1.337, 
                                ppa = 1.337, 
                                total_ppa = 1.337, 
                                line_yards = 1.337, 
                                line_yards_total = 1.337, 
                                second_level_yards = 1.337, 
                                second_level_yards_total = 1.337, 
                                open_field_yards = 1.337, 
                                open_field_yards_total = 1.337, 
                                stuff_rate = 1.337, 
                                power_success = 1.337, 
                                explosiveness = 1.337, ), 
                            middle = , 
                            left = , ), 
                        game_id = 56, 
                        season = 56, 
                        week = 56, 
                        season_type = 'regular', 
                        player_id = '', 
                        player = '', 
                        team = '', 
                        conference = '', 
                        opponent = '', )
                    ],
                passing = [
                    cfbd.models.player_passing_game.PlayerPassingGame(
                        attempts = 56, 
                        completions = 56, 
                        incompletions = 56, 
                        interceptions = 56, 
                        completion_rate = 1.337, 
                        air_yards_attempts_available = 56, 
                        total_air_yards = 56, 
                        average_depth_of_target = 1.337, 
                        total_yards_attempts_available = 56, 
                        total_yards = 56, 
                        yards_after_catch_attempts_available = 56, 
                        total_yards_after_catch = 56, 
                        average_yards_after_catch = 1.337, 
                        success_rate = 1.337, 
                        ppa = 1.337, 
                        total_ppa = 1.337, 
                        explosiveness = 1.337, 
                        ppa_attempts_available = 56, 
                        success_attempts_available = 56, 
                        successful_attempts = 56, 
                        successful_ppa_attempts_available = 56, 
                        location_eligible_attempts = 56, 
                        location_available_attempts = 56, 
                        locations = cfbd.models.passing_locations.PassingLocations(
                            short_left = cfbd.models.passing_location_production.PassingLocationProduction(
                                attempts = 56, 
                                completions = 56, 
                                incompletions = 56, 
                                interceptions = 56, 
                                completion_rate = 1.337, 
                                air_yards_attempts_available = 56, 
                                total_air_yards = 56, 
                                average_depth_of_target = 1.337, 
                                total_yards_attempts_available = 56, 
                                total_yards = 56, 
                                yards_after_catch_attempts_available = 56, 
                                total_yards_after_catch = 56, 
                                average_yards_after_catch = 1.337, 
                                success_rate = 1.337, 
                                ppa = 1.337, 
                                total_ppa = 1.337, 
                                explosiveness = 1.337, 
                                ppa_attempts_available = 56, 
                                success_attempts_available = 56, 
                                successful_attempts = 56, 
                                successful_ppa_attempts_available = 56, 
                                yards_per_attempt = 1.337, 
                                air_yards_per_attempt = 1.337, ), 
                            short_middle = cfbd.models.passing_location_production.PassingLocationProduction(
                                attempts = 56, 
                                completions = 56, 
                                incompletions = 56, 
                                interceptions = 56, 
                                completion_rate = 1.337, 
                                air_yards_attempts_available = 56, 
                                total_air_yards = 56, 
                                average_depth_of_target = 1.337, 
                                total_yards_attempts_available = 56, 
                                total_yards = 56, 
                                yards_after_catch_attempts_available = 56, 
                                total_yards_after_catch = 56, 
                                average_yards_after_catch = 1.337, 
                                success_rate = 1.337, 
                                ppa = 1.337, 
                                total_ppa = 1.337, 
                                explosiveness = 1.337, 
                                ppa_attempts_available = 56, 
                                success_attempts_available = 56, 
                                successful_attempts = 56, 
                                successful_ppa_attempts_available = 56, 
                                yards_per_attempt = 1.337, 
                                air_yards_per_attempt = 1.337, ), 
                            short_right = , 
                            deep_left = , 
                            deep_middle = , 
                            deep_right = , 
                            unknown = , ), 
                        game_id = 56, 
                        season = 56, 
                        week = 56, 
                        season_type = 'regular', 
                        player_id = '', 
                        player = '', 
                        team = '', 
                        conference = '', 
                        opponent = '', )
                    ],
        )
        """

    def testAdvancedBoxScorePlayers(self):
        """Test AdvancedBoxScorePlayers"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
