# coding: utf-8

"""
    College Football Data API

    This is an API for query various college football datasets and analytics. API keys can be acquired from the CollegeFootballData.com website.

    The version of the OpenAPI document: 5.19.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cfbd.models.playoff_participant import PlayoffParticipant  # noqa: E501

class TestPlayoffParticipant(unittest.TestCase):
    """PlayoffParticipant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlayoffParticipant:
        """Test PlayoffParticipant
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlayoffParticipant`
        """
        model = PlayoffParticipant()  # noqa: E501
        if include_optional:
            return PlayoffParticipant(
                team = cfbd.models.playoff_team.PlayoffTeam(
                    id = 56, 
                    school = '', 
                    conference = '', ),
                committee_rank = 56,
                seed = 56,
                bid_type = 'automatic',
                qualification_reason = '',
                conference_champion = True,
                qualifying_conference = '',
                first_round_bye = True,
                outcome = 'active',
                eliminated_round = 'first_round'
            )
        else:
            return PlayoffParticipant(
                team = cfbd.models.playoff_team.PlayoffTeam(
                    id = 56, 
                    school = '', 
                    conference = '', ),
                committee_rank = 56,
                seed = 56,
                bid_type = 'automatic',
                qualification_reason = '',
                conference_champion = True,
                qualifying_conference = '',
                first_round_bye = True,
                outcome = 'active',
                eliminated_round = 'first_round',
        )
        """

    def testPlayoffParticipant(self):
        """Test PlayoffParticipant"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
