# coding: utf-8

"""
    College Football Data API

    This API is in limited Beta for Patreon subscribers. It may have bugs and is subject to changes. API keys can be acquired from the CollegeFootballData.com website.

    The version of the OpenAPI document: 5.1.2
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cfbd.models.recruit_classification import RecruitClassification  # noqa: E501

class TestRecruitClassification(unittest.TestCase):
    """RecruitClassification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecruitClassification(self):
        """Test RecruitClassification"""
        # inst = RecruitClassification()

if __name__ == '__main__':
    unittest.main()
