# coding: utf-8

"""
    College Football Data API

    Build college football applications, models, and analysis with game, team, player, recruiting, ranking, and advanced metrics data. Request an API key at CollegeFootballData.com.

    The version of the OpenAPI document: 5.26.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import re  # noqa: F401
import io
import warnings

from pydantic import validate_arguments, ValidationError

from typing_extensions import Annotated
from pydantic import Field, StrictInt, StrictStr

from typing import List, Optional

from cfbd.models.division_classification import DivisionClassification
from cfbd.models.pass_outcome import PassOutcome
from cfbd.models.passing_play import PassingPlay
from cfbd.models.player_passing_game import PlayerPassingGame
from cfbd.models.player_passing_season import PlayerPassingSeason
from cfbd.models.season_type import SeasonType
from cfbd.models.team_passing_game import TeamPassingGame
from cfbd.models.team_passing_season import TeamPassingSeason

from cfbd.api_client import ApiClient
from cfbd.api_response import ApiResponse
from cfbd.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class PassingApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    def get_passing_plays(self, year : Annotated[StrictInt, Field(..., description="Season year.")], team : Annotated[Optional[StrictStr], Field(description="Team name on either side of the pass. Either team or week is required.")] = None, week : Annotated[Optional[StrictInt], Field(description="Week number. Either team or week is required.")] = None, game_id : Annotated[Optional[StrictInt], Field(description="Game ID.")] = None, season_type : Annotated[Optional[SeasonType], Field(description="Season type.")] = None, offense : Annotated[Optional[StrictStr], Field(description="Offensive team name.")] = None, defense : Annotated[Optional[StrictStr], Field(description="Defensive team name.")] = None, conference : Annotated[Optional[StrictStr], Field(description="Conference name or abbreviation on either side of the pass.")] = None, passer_id : Annotated[Optional[StrictStr], Field(description="Passer athlete ID.")] = None, target_id : Annotated[Optional[StrictStr], Field(description="Intended target athlete ID.")] = None, outcome : Annotated[Optional[PassOutcome], Field(description="Pass outcome.")] = None, classification : Annotated[Optional[DivisionClassification], Field(description="Division classification. Defaults to `fbs`.")] = None, **kwargs) -> List[PassingPlay]:  # noqa: E501
        """get_passing_plays  # noqa: E501

        Returns enriched pass attempts.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_passing_plays(year, team, week, game_id, season_type, offense, defense, conference, passer_id, target_id, outcome, classification, async_req=True)
        >>> result = thread.get()

        :param year: Season year. (required)
        :type year: int
        :param team: Team name on either side of the pass. Either team or week is required.
        :type team: str
        :param week: Week number. Either team or week is required.
        :type week: int
        :param game_id: Game ID.
        :type game_id: int
        :param season_type: Season type.
        :type season_type: SeasonType
        :param offense: Offensive team name.
        :type offense: str
        :param defense: Defensive team name.
        :type defense: str
        :param conference: Conference name or abbreviation on either side of the pass.
        :type conference: str
        :param passer_id: Passer athlete ID.
        :type passer_id: str
        :param target_id: Intended target athlete ID.
        :type target_id: str
        :param outcome: Pass outcome.
        :type outcome: PassOutcome
        :param classification: Division classification. Defaults to `fbs`.
        :type classification: DivisionClassification
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: List[PassingPlay]
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_passing_plays_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.get_passing_plays_with_http_info(year, team, week, game_id, season_type, offense, defense, conference, passer_id, target_id, outcome, classification, **kwargs)  # noqa: E501

    @validate_arguments
    def get_passing_plays_with_http_info(self, year : Annotated[StrictInt, Field(..., description="Season year.")], team : Annotated[Optional[StrictStr], Field(description="Team name on either side of the pass. Either team or week is required.")] = None, week : Annotated[Optional[StrictInt], Field(description="Week number. Either team or week is required.")] = None, game_id : Annotated[Optional[StrictInt], Field(description="Game ID.")] = None, season_type : Annotated[Optional[SeasonType], Field(description="Season type.")] = None, offense : Annotated[Optional[StrictStr], Field(description="Offensive team name.")] = None, defense : Annotated[Optional[StrictStr], Field(description="Defensive team name.")] = None, conference : Annotated[Optional[StrictStr], Field(description="Conference name or abbreviation on either side of the pass.")] = None, passer_id : Annotated[Optional[StrictStr], Field(description="Passer athlete ID.")] = None, target_id : Annotated[Optional[StrictStr], Field(description="Intended target athlete ID.")] = None, outcome : Annotated[Optional[PassOutcome], Field(description="Pass outcome.")] = None, classification : Annotated[Optional[DivisionClassification], Field(description="Division classification. Defaults to `fbs`.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """get_passing_plays  # noqa: E501

        Returns enriched pass attempts.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_passing_plays_with_http_info(year, team, week, game_id, season_type, offense, defense, conference, passer_id, target_id, outcome, classification, async_req=True)
        >>> result = thread.get()

        :param year: Season year. (required)
        :type year: int
        :param team: Team name on either side of the pass. Either team or week is required.
        :type team: str
        :param week: Week number. Either team or week is required.
        :type week: int
        :param game_id: Game ID.
        :type game_id: int
        :param season_type: Season type.
        :type season_type: SeasonType
        :param offense: Offensive team name.
        :type offense: str
        :param defense: Defensive team name.
        :type defense: str
        :param conference: Conference name or abbreviation on either side of the pass.
        :type conference: str
        :param passer_id: Passer athlete ID.
        :type passer_id: str
        :param target_id: Intended target athlete ID.
        :type target_id: str
        :param outcome: Pass outcome.
        :type outcome: PassOutcome
        :param classification: Division classification. Defaults to `fbs`.
        :type classification: DivisionClassification
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(List[PassingPlay], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'year',
            'team',
            'week',
            'game_id',
            'season_type',
            'offense',
            'defense',
            'conference',
            'passer_id',
            'target_id',
            'outcome',
            'classification'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_passing_plays" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('year') is not None:  # noqa: E501
            _query_params.append(('year', _params['year']))

        if _params.get('team') is not None:  # noqa: E501
            _query_params.append(('team', _params['team']))

        if _params.get('week') is not None:  # noqa: E501
            _query_params.append(('week', _params['week']))

        if _params.get('game_id') is not None:  # noqa: E501
            _query_params.append(('gameId', _params['game_id']))

        if _params.get('season_type') is not None:  # noqa: E501
            _query_params.append(('seasonType', _params['season_type'].value))

        if _params.get('offense') is not None:  # noqa: E501
            _query_params.append(('offense', _params['offense']))

        if _params.get('defense') is not None:  # noqa: E501
            _query_params.append(('defense', _params['defense']))

        if _params.get('conference') is not None:  # noqa: E501
            _query_params.append(('conference', _params['conference']))

        if _params.get('passer_id') is not None:  # noqa: E501
            _query_params.append(('passerId', _params['passer_id']))

        if _params.get('target_id') is not None:  # noqa: E501
            _query_params.append(('targetId', _params['target_id']))

        if _params.get('outcome') is not None:  # noqa: E501
            _query_params.append(('outcome', _params['outcome'].value))

        if _params.get('classification') is not None:  # noqa: E501
            _query_params.append(('classification', _params['classification'].value))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['apiKey']  # noqa: E501

        _response_types_map = {
            '200': "List[PassingPlay]",
        }

        return self.api_client.call_api(
            '/passing/plays', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def get_player_passing_by_game(self, year : Annotated[StrictInt, Field(..., description="Season year. Required.")], week : Annotated[Optional[StrictInt], Field(description="Week number. Either passerId, team, or week is required.")] = None, season_type : Annotated[Optional[SeasonType], Field(description="Season type.")] = None, team : Annotated[Optional[StrictStr], Field(description="Team name. Either passerId, team, or week is required.")] = None, conference : Annotated[Optional[StrictStr], Field(description="Conference name or abbreviation.")] = None, passer_id : Annotated[Optional[StrictStr], Field(description="Passer athlete ID. Either passerId, team, or week is required.")] = None, classification : Annotated[Optional[DivisionClassification], Field(description="Division classification. Defaults to `fbs`.")] = None, **kwargs) -> List[PlayerPassingGame]:  # noqa: E501
        """get_player_passing_by_game  # noqa: E501

        Returns passer production by game.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_player_passing_by_game(year, week, season_type, team, conference, passer_id, classification, async_req=True)
        >>> result = thread.get()

        :param year: Season year. Required. (required)
        :type year: int
        :param week: Week number. Either passerId, team, or week is required.
        :type week: int
        :param season_type: Season type.
        :type season_type: SeasonType
        :param team: Team name. Either passerId, team, or week is required.
        :type team: str
        :param conference: Conference name or abbreviation.
        :type conference: str
        :param passer_id: Passer athlete ID. Either passerId, team, or week is required.
        :type passer_id: str
        :param classification: Division classification. Defaults to `fbs`.
        :type classification: DivisionClassification
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: List[PlayerPassingGame]
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_player_passing_by_game_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.get_player_passing_by_game_with_http_info(year, week, season_type, team, conference, passer_id, classification, **kwargs)  # noqa: E501

    @validate_arguments
    def get_player_passing_by_game_with_http_info(self, year : Annotated[StrictInt, Field(..., description="Season year. Required.")], week : Annotated[Optional[StrictInt], Field(description="Week number. Either passerId, team, or week is required.")] = None, season_type : Annotated[Optional[SeasonType], Field(description="Season type.")] = None, team : Annotated[Optional[StrictStr], Field(description="Team name. Either passerId, team, or week is required.")] = None, conference : Annotated[Optional[StrictStr], Field(description="Conference name or abbreviation.")] = None, passer_id : Annotated[Optional[StrictStr], Field(description="Passer athlete ID. Either passerId, team, or week is required.")] = None, classification : Annotated[Optional[DivisionClassification], Field(description="Division classification. Defaults to `fbs`.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """get_player_passing_by_game  # noqa: E501

        Returns passer production by game.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_player_passing_by_game_with_http_info(year, week, season_type, team, conference, passer_id, classification, async_req=True)
        >>> result = thread.get()

        :param year: Season year. Required. (required)
        :type year: int
        :param week: Week number. Either passerId, team, or week is required.
        :type week: int
        :param season_type: Season type.
        :type season_type: SeasonType
        :param team: Team name. Either passerId, team, or week is required.
        :type team: str
        :param conference: Conference name or abbreviation.
        :type conference: str
        :param passer_id: Passer athlete ID. Either passerId, team, or week is required.
        :type passer_id: str
        :param classification: Division classification. Defaults to `fbs`.
        :type classification: DivisionClassification
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(List[PlayerPassingGame], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'year',
            'week',
            'season_type',
            'team',
            'conference',
            'passer_id',
            'classification'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_player_passing_by_game" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('year') is not None:  # noqa: E501
            _query_params.append(('year', _params['year']))

        if _params.get('week') is not None:  # noqa: E501
            _query_params.append(('week', _params['week']))

        if _params.get('season_type') is not None:  # noqa: E501
            _query_params.append(('seasonType', _params['season_type'].value))

        if _params.get('team') is not None:  # noqa: E501
            _query_params.append(('team', _params['team']))

        if _params.get('conference') is not None:  # noqa: E501
            _query_params.append(('conference', _params['conference']))

        if _params.get('passer_id') is not None:  # noqa: E501
            _query_params.append(('passerId', _params['passer_id']))

        if _params.get('classification') is not None:  # noqa: E501
            _query_params.append(('classification', _params['classification'].value))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['apiKey']  # noqa: E501

        _response_types_map = {
            '200': "List[PlayerPassingGame]",
        }

        return self.api_client.call_api(
            '/passing/players/games', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def get_player_passing_by_season(self, year : Annotated[Optional[StrictInt], Field(description="Season year. Required unless passerId is specified.")] = None, season_type : Annotated[Optional[SeasonType], Field(description="Season type.")] = None, team : Annotated[Optional[StrictStr], Field(description="Team name.")] = None, conference : Annotated[Optional[StrictStr], Field(description="Conference name or abbreviation.")] = None, passer_id : Annotated[Optional[StrictStr], Field(description="Passer athlete ID. Required unless year is specified.")] = None, classification : Annotated[Optional[DivisionClassification], Field(description="Division classification. Defaults to `fbs`.")] = None, **kwargs) -> List[PlayerPassingSeason]:  # noqa: E501
        """get_player_passing_by_season  # noqa: E501

        Returns passer production by season.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_player_passing_by_season(year, season_type, team, conference, passer_id, classification, async_req=True)
        >>> result = thread.get()

        :param year: Season year. Required unless passerId is specified.
        :type year: int
        :param season_type: Season type.
        :type season_type: SeasonType
        :param team: Team name.
        :type team: str
        :param conference: Conference name or abbreviation.
        :type conference: str
        :param passer_id: Passer athlete ID. Required unless year is specified.
        :type passer_id: str
        :param classification: Division classification. Defaults to `fbs`.
        :type classification: DivisionClassification
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: List[PlayerPassingSeason]
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_player_passing_by_season_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.get_player_passing_by_season_with_http_info(year, season_type, team, conference, passer_id, classification, **kwargs)  # noqa: E501

    @validate_arguments
    def get_player_passing_by_season_with_http_info(self, year : Annotated[Optional[StrictInt], Field(description="Season year. Required unless passerId is specified.")] = None, season_type : Annotated[Optional[SeasonType], Field(description="Season type.")] = None, team : Annotated[Optional[StrictStr], Field(description="Team name.")] = None, conference : Annotated[Optional[StrictStr], Field(description="Conference name or abbreviation.")] = None, passer_id : Annotated[Optional[StrictStr], Field(description="Passer athlete ID. Required unless year is specified.")] = None, classification : Annotated[Optional[DivisionClassification], Field(description="Division classification. Defaults to `fbs`.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """get_player_passing_by_season  # noqa: E501

        Returns passer production by season.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_player_passing_by_season_with_http_info(year, season_type, team, conference, passer_id, classification, async_req=True)
        >>> result = thread.get()

        :param year: Season year. Required unless passerId is specified.
        :type year: int
        :param season_type: Season type.
        :type season_type: SeasonType
        :param team: Team name.
        :type team: str
        :param conference: Conference name or abbreviation.
        :type conference: str
        :param passer_id: Passer athlete ID. Required unless year is specified.
        :type passer_id: str
        :param classification: Division classification. Defaults to `fbs`.
        :type classification: DivisionClassification
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(List[PlayerPassingSeason], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'year',
            'season_type',
            'team',
            'conference',
            'passer_id',
            'classification'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_player_passing_by_season" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('year') is not None:  # noqa: E501
            _query_params.append(('year', _params['year']))

        if _params.get('season_type') is not None:  # noqa: E501
            _query_params.append(('seasonType', _params['season_type'].value))

        if _params.get('team') is not None:  # noqa: E501
            _query_params.append(('team', _params['team']))

        if _params.get('conference') is not None:  # noqa: E501
            _query_params.append(('conference', _params['conference']))

        if _params.get('passer_id') is not None:  # noqa: E501
            _query_params.append(('passerId', _params['passer_id']))

        if _params.get('classification') is not None:  # noqa: E501
            _query_params.append(('classification', _params['classification'].value))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['apiKey']  # noqa: E501

        _response_types_map = {
            '200': "List[PlayerPassingSeason]",
        }

        return self.api_client.call_api(
            '/passing/players/season', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def get_team_passing_by_game(self, year : Annotated[StrictInt, Field(..., description="Season year. Required.")], week : Annotated[Optional[StrictInt], Field(description="Week number. Either team or week is required.")] = None, season_type : Annotated[Optional[SeasonType], Field(description="Season type.")] = None, team : Annotated[Optional[StrictStr], Field(description="Team name. Either team or week is required.")] = None, conference : Annotated[Optional[StrictStr], Field(description="Conference name or abbreviation.")] = None, classification : Annotated[Optional[DivisionClassification], Field(description="Division classification. Defaults to `fbs`.")] = None, **kwargs) -> List[TeamPassingGame]:  # noqa: E501
        """get_team_passing_by_game  # noqa: E501

        Returns team passing production by game.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_team_passing_by_game(year, week, season_type, team, conference, classification, async_req=True)
        >>> result = thread.get()

        :param year: Season year. Required. (required)
        :type year: int
        :param week: Week number. Either team or week is required.
        :type week: int
        :param season_type: Season type.
        :type season_type: SeasonType
        :param team: Team name. Either team or week is required.
        :type team: str
        :param conference: Conference name or abbreviation.
        :type conference: str
        :param classification: Division classification. Defaults to `fbs`.
        :type classification: DivisionClassification
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: List[TeamPassingGame]
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_team_passing_by_game_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.get_team_passing_by_game_with_http_info(year, week, season_type, team, conference, classification, **kwargs)  # noqa: E501

    @validate_arguments
    def get_team_passing_by_game_with_http_info(self, year : Annotated[StrictInt, Field(..., description="Season year. Required.")], week : Annotated[Optional[StrictInt], Field(description="Week number. Either team or week is required.")] = None, season_type : Annotated[Optional[SeasonType], Field(description="Season type.")] = None, team : Annotated[Optional[StrictStr], Field(description="Team name. Either team or week is required.")] = None, conference : Annotated[Optional[StrictStr], Field(description="Conference name or abbreviation.")] = None, classification : Annotated[Optional[DivisionClassification], Field(description="Division classification. Defaults to `fbs`.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """get_team_passing_by_game  # noqa: E501

        Returns team passing production by game.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_team_passing_by_game_with_http_info(year, week, season_type, team, conference, classification, async_req=True)
        >>> result = thread.get()

        :param year: Season year. Required. (required)
        :type year: int
        :param week: Week number. Either team or week is required.
        :type week: int
        :param season_type: Season type.
        :type season_type: SeasonType
        :param team: Team name. Either team or week is required.
        :type team: str
        :param conference: Conference name or abbreviation.
        :type conference: str
        :param classification: Division classification. Defaults to `fbs`.
        :type classification: DivisionClassification
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(List[TeamPassingGame], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'year',
            'week',
            'season_type',
            'team',
            'conference',
            'classification'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_team_passing_by_game" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('year') is not None:  # noqa: E501
            _query_params.append(('year', _params['year']))

        if _params.get('week') is not None:  # noqa: E501
            _query_params.append(('week', _params['week']))

        if _params.get('season_type') is not None:  # noqa: E501
            _query_params.append(('seasonType', _params['season_type'].value))

        if _params.get('team') is not None:  # noqa: E501
            _query_params.append(('team', _params['team']))

        if _params.get('conference') is not None:  # noqa: E501
            _query_params.append(('conference', _params['conference']))

        if _params.get('classification') is not None:  # noqa: E501
            _query_params.append(('classification', _params['classification'].value))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['apiKey']  # noqa: E501

        _response_types_map = {
            '200': "List[TeamPassingGame]",
        }

        return self.api_client.call_api(
            '/passing/teams/games', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def get_team_passing_by_season(self, year : Annotated[Optional[StrictInt], Field(description="Season year. Required unless team is specified.")] = None, season_type : Annotated[Optional[SeasonType], Field(description="Season type.")] = None, team : Annotated[Optional[StrictStr], Field(description="Team name. Required unless year is specified.")] = None, conference : Annotated[Optional[StrictStr], Field(description="Conference name or abbreviation.")] = None, classification : Annotated[Optional[DivisionClassification], Field(description="Division classification. Defaults to `fbs`.")] = None, **kwargs) -> List[TeamPassingSeason]:  # noqa: E501
        """get_team_passing_by_season  # noqa: E501

        Returns team passing production by season.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_team_passing_by_season(year, season_type, team, conference, classification, async_req=True)
        >>> result = thread.get()

        :param year: Season year. Required unless team is specified.
        :type year: int
        :param season_type: Season type.
        :type season_type: SeasonType
        :param team: Team name. Required unless year is specified.
        :type team: str
        :param conference: Conference name or abbreviation.
        :type conference: str
        :param classification: Division classification. Defaults to `fbs`.
        :type classification: DivisionClassification
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: List[TeamPassingSeason]
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_team_passing_by_season_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.get_team_passing_by_season_with_http_info(year, season_type, team, conference, classification, **kwargs)  # noqa: E501

    @validate_arguments
    def get_team_passing_by_season_with_http_info(self, year : Annotated[Optional[StrictInt], Field(description="Season year. Required unless team is specified.")] = None, season_type : Annotated[Optional[SeasonType], Field(description="Season type.")] = None, team : Annotated[Optional[StrictStr], Field(description="Team name. Required unless year is specified.")] = None, conference : Annotated[Optional[StrictStr], Field(description="Conference name or abbreviation.")] = None, classification : Annotated[Optional[DivisionClassification], Field(description="Division classification. Defaults to `fbs`.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """get_team_passing_by_season  # noqa: E501

        Returns team passing production by season.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_team_passing_by_season_with_http_info(year, season_type, team, conference, classification, async_req=True)
        >>> result = thread.get()

        :param year: Season year. Required unless team is specified.
        :type year: int
        :param season_type: Season type.
        :type season_type: SeasonType
        :param team: Team name. Required unless year is specified.
        :type team: str
        :param conference: Conference name or abbreviation.
        :type conference: str
        :param classification: Division classification. Defaults to `fbs`.
        :type classification: DivisionClassification
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(List[TeamPassingSeason], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'year',
            'season_type',
            'team',
            'conference',
            'classification'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_team_passing_by_season" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('year') is not None:  # noqa: E501
            _query_params.append(('year', _params['year']))

        if _params.get('season_type') is not None:  # noqa: E501
            _query_params.append(('seasonType', _params['season_type'].value))

        if _params.get('team') is not None:  # noqa: E501
            _query_params.append(('team', _params['team']))

        if _params.get('conference') is not None:  # noqa: E501
            _query_params.append(('conference', _params['conference']))

        if _params.get('classification') is not None:  # noqa: E501
            _query_params.append(('classification', _params['classification'].value))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['apiKey']  # noqa: E501

        _response_types_map = {
            '200': "List[TeamPassingSeason]",
        }

        return self.api_client.call_api(
            '/passing/teams/season', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
