# coding: utf-8

"""
    College Football Data API

    This is an API for query various college football datasets and analytics. API keys can be acquired from the CollegeFootballData.com website.

    The version of the OpenAPI document: 5.18.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist
from cfbd.models.playoff_competition_cfp import PlayoffCompetitionCfp
from cfbd.models.playoff_participant import PlayoffParticipant
from cfbd.models.playoff_round_record import PlayoffRoundRecord
from cfbd.models.playoff_status import PlayoffStatus
from cfbd.models.playoff_team import PlayoffTeam

class CfpPlayoff(BaseModel):
    """
    CfpPlayoff
    """
    season: StrictInt = Field(...)
    competition: PlayoffCompetitionCfp = Field(...)
    format: StrictStr = Field(...)
    team_count: StrictInt = Field(default=..., alias="teamCount")
    status: PlayoffStatus = Field(...)
    participants: conlist(PlayoffParticipant) = Field(...)
    rounds: conlist(PlayoffRoundRecord) = Field(...)
    champion: Optional[PlayoffTeam] = Field(...)
    __properties = ["season", "competition", "format", "teamCount", "status", "participants", "rounds", "champion"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CfpPlayoff:
        """Create an instance of CfpPlayoff from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in participants (list)
        _items = []
        if self.participants:
            for _item in self.participants:
                if _item:
                    _items.append(_item.to_dict())
            _dict['participants'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in rounds (list)
        _items = []
        if self.rounds:
            for _item in self.rounds:
                if _item:
                    _items.append(_item.to_dict())
            _dict['rounds'] = _items
        # override the default output from pydantic by calling `to_dict()` of champion
        if self.champion:
            _dict['champion'] = self.champion.to_dict()
        # set to None if champion (nullable) is None
        # and __fields_set__ contains the field
        if self.champion is None and "champion" in self.__fields_set__:
            _dict['champion'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CfpPlayoff:
        """Create an instance of CfpPlayoff from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CfpPlayoff.parse_obj(obj)

        _obj = CfpPlayoff.parse_obj({
            "season": obj.get("season"),
            "competition": obj.get("competition"),
            "format": obj.get("format"),
            "team_count": obj.get("teamCount"),
            "status": obj.get("status"),
            "participants": [PlayoffParticipant.from_dict(_item) for _item in obj.get("participants")] if obj.get("participants") is not None else None,
            "rounds": [PlayoffRoundRecord.from_dict(_item) for _item in obj.get("rounds")] if obj.get("rounds") is not None else None,
            "champion": PlayoffTeam.from_dict(obj.get("champion")) if obj.get("champion") is not None else None
        })
        return _obj


