# coding: utf-8

"""
    College Football Data API

    Build college football applications, models, and analysis with game, team, player, recruiting, ranking, and advanced metrics data. Request an API key at CollegeFootballData.com.

    The version of the OpenAPI document: 5.23.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt

class CoachCareer(BaseModel):
    """
    CoachCareer
    """
    games: StrictInt = Field(...)
    wins: StrictInt = Field(...)
    losses: StrictInt = Field(...)
    ties: StrictInt = Field(...)
    win_percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="winPercentage")
    seasons: StrictInt = Field(...)
    teams: StrictInt = Field(...)
    first_year: StrictInt = Field(default=..., alias="firstYear")
    last_year: StrictInt = Field(default=..., alias="lastYear")
    __properties = ["games", "wins", "losses", "ties", "winPercentage", "seasons", "teams", "firstYear", "lastYear"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CoachCareer:
        """Create an instance of CoachCareer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if win_percentage (nullable) is None
        # and __fields_set__ contains the field
        if self.win_percentage is None and "win_percentage" in self.__fields_set__:
            _dict['winPercentage'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CoachCareer:
        """Create an instance of CoachCareer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CoachCareer.parse_obj(obj)

        _obj = CoachCareer.parse_obj({
            "games": obj.get("games"),
            "wins": obj.get("wins"),
            "losses": obj.get("losses"),
            "ties": obj.get("ties"),
            "win_percentage": obj.get("winPercentage"),
            "seasons": obj.get("seasons"),
            "teams": obj.get("teams"),
            "first_year": obj.get("firstYear"),
            "last_year": obj.get("lastYear")
        })
        return _obj


