# coding: utf-8

"""
    College Football Data API

    Build college football applications, models, and analysis with game, team, player, recruiting, ranking, and advanced metrics data. Request an API key at CollegeFootballData.com.

    The version of the OpenAPI document: 5.24.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr
from cfbd.models.coach_alma_mater import CoachAlmaMater
from cfbd.models.coach_career import CoachCareer
from cfbd.models.coach_season_team_reference import CoachSeasonTeamReference

class CoachProfile(BaseModel):
    """
    CoachProfile
    """
    id: StrictInt = Field(...)
    first_name: StrictStr = Field(default=..., alias="firstName")
    last_name: StrictStr = Field(default=..., alias="lastName")
    display_name: Optional[StrictStr] = Field(default=..., alias="displayName")
    current_team: Optional[CoachSeasonTeamReference] = Field(default=..., alias="currentTeam")
    career: CoachCareer = Field(...)
    birth_date: Optional[StrictStr] = Field(default=..., alias="birthDate")
    alma_mater: Optional[CoachAlmaMater] = Field(default=..., alias="almaMater")
    graduation_year: Optional[StrictInt] = Field(default=..., alias="graduationYear")
    wikidata_id: Optional[StrictStr] = Field(default=..., alias="wikidataId")
    hall_of_fame_year: Optional[StrictInt] = Field(default=..., alias="hallOfFameYear")
    __properties = ["id", "firstName", "lastName", "displayName", "currentTeam", "career", "birthDate", "almaMater", "graduationYear", "wikidataId", "hallOfFameYear"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CoachProfile:
        """Create an instance of CoachProfile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of current_team
        if self.current_team:
            _dict['currentTeam'] = self.current_team.to_dict()
        # override the default output from pydantic by calling `to_dict()` of career
        if self.career:
            _dict['career'] = self.career.to_dict()
        # override the default output from pydantic by calling `to_dict()` of alma_mater
        if self.alma_mater:
            _dict['almaMater'] = self.alma_mater.to_dict()
        # set to None if display_name (nullable) is None
        # and __fields_set__ contains the field
        if self.display_name is None and "display_name" in self.__fields_set__:
            _dict['displayName'] = None

        # set to None if current_team (nullable) is None
        # and __fields_set__ contains the field
        if self.current_team is None and "current_team" in self.__fields_set__:
            _dict['currentTeam'] = None

        # set to None if birth_date (nullable) is None
        # and __fields_set__ contains the field
        if self.birth_date is None and "birth_date" in self.__fields_set__:
            _dict['birthDate'] = None

        # set to None if alma_mater (nullable) is None
        # and __fields_set__ contains the field
        if self.alma_mater is None and "alma_mater" in self.__fields_set__:
            _dict['almaMater'] = None

        # set to None if graduation_year (nullable) is None
        # and __fields_set__ contains the field
        if self.graduation_year is None and "graduation_year" in self.__fields_set__:
            _dict['graduationYear'] = None

        # set to None if wikidata_id (nullable) is None
        # and __fields_set__ contains the field
        if self.wikidata_id is None and "wikidata_id" in self.__fields_set__:
            _dict['wikidataId'] = None

        # set to None if hall_of_fame_year (nullable) is None
        # and __fields_set__ contains the field
        if self.hall_of_fame_year is None and "hall_of_fame_year" in self.__fields_set__:
            _dict['hallOfFameYear'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CoachProfile:
        """Create an instance of CoachProfile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CoachProfile.parse_obj(obj)

        _obj = CoachProfile.parse_obj({
            "id": obj.get("id"),
            "first_name": obj.get("firstName"),
            "last_name": obj.get("lastName"),
            "display_name": obj.get("displayName"),
            "current_team": CoachSeasonTeamReference.from_dict(obj.get("currentTeam")) if obj.get("currentTeam") is not None else None,
            "career": CoachCareer.from_dict(obj.get("career")) if obj.get("career") is not None else None,
            "birth_date": obj.get("birthDate"),
            "alma_mater": CoachAlmaMater.from_dict(obj.get("almaMater")) if obj.get("almaMater") is not None else None,
            "graduation_year": obj.get("graduationYear"),
            "wikidata_id": obj.get("wikidataId"),
            "hall_of_fame_year": obj.get("hallOfFameYear")
        })
        return _obj


