# coding: utf-8

"""
    College Football Data API

    Build college football applications, models, and analysis with game, team, player, recruiting, ranking, and advanced metrics data. Request an API key at CollegeFootballData.com.

    The version of the OpenAPI document: 5.31.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field
from cfbd.models.free_preview_team import FreePreviewTeam
from cfbd.models.preview_section_preview_broadcast_array import PreviewSectionPreviewBroadcastArray
from cfbd.models.preview_section_selected_odds import PreviewSectionSelectedOdds
from cfbd.models.preview_section_series_history import PreviewSectionSeriesHistory

class FreePreviewAnalysis(BaseModel):
    """
    FreePreviewAnalysis
    """
    broadcasts: PreviewSectionPreviewBroadcastArray = Field(...)
    odds: PreviewSectionSelectedOdds = Field(...)
    home: FreePreviewTeam = Field(...)
    away: FreePreviewTeam = Field(...)
    series: PreviewSectionSeriesHistory = Field(...)
    __properties = ["broadcasts", "odds", "home", "away", "series"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> FreePreviewAnalysis:
        """Create an instance of FreePreviewAnalysis from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of broadcasts
        if self.broadcasts:
            _dict['broadcasts'] = self.broadcasts.to_dict()
        # override the default output from pydantic by calling `to_dict()` of odds
        if self.odds:
            _dict['odds'] = self.odds.to_dict()
        # override the default output from pydantic by calling `to_dict()` of home
        if self.home:
            _dict['home'] = self.home.to_dict()
        # override the default output from pydantic by calling `to_dict()` of away
        if self.away:
            _dict['away'] = self.away.to_dict()
        # override the default output from pydantic by calling `to_dict()` of series
        if self.series:
            _dict['series'] = self.series.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> FreePreviewAnalysis:
        """Create an instance of FreePreviewAnalysis from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return FreePreviewAnalysis.parse_obj(obj)

        _obj = FreePreviewAnalysis.parse_obj({
            "broadcasts": PreviewSectionPreviewBroadcastArray.from_dict(obj.get("broadcasts")) if obj.get("broadcasts") is not None else None,
            "odds": PreviewSectionSelectedOdds.from_dict(obj.get("odds")) if obj.get("odds") is not None else None,
            "home": FreePreviewTeam.from_dict(obj.get("home")) if obj.get("home") is not None else None,
            "away": FreePreviewTeam.from_dict(obj.get("away")) if obj.get("away") is not None else None,
            "series": PreviewSectionSeriesHistory.from_dict(obj.get("series")) if obj.get("series") is not None else None
        })
        return _obj


