# coding: utf-8

"""
    College Football Data API

    Build college football applications, models, and analysis with game, team, player, recruiting, ranking, and advanced metrics data. Request an API key at CollegeFootballData.com.

    The version of the OpenAPI document: 5.30.1
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Dict
from pydantic import BaseModel, Field, StrictStr
from cfbd.models.field_errors_value import FieldErrorsValue

class GetCoachTenures400Response(BaseModel):
    """
    GetCoachTenures400Response
    """
    details: Dict[str, FieldErrorsValue] = Field(...)
    message: StrictStr = Field(...)
    __properties = ["details", "message"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GetCoachTenures400Response:
        """Create an instance of GetCoachTenures400Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each value in details (dict)
        _field_dict = {}
        if self.details:
            for _key in self.details:
                if self.details[_key]:
                    _field_dict[_key] = self.details[_key].to_dict()
            _dict['details'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GetCoachTenures400Response:
        """Create an instance of GetCoachTenures400Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GetCoachTenures400Response.parse_obj(obj)

        _obj = GetCoachTenures400Response.parse_obj({
            "details": dict(
                (_k, FieldErrorsValue.from_dict(_v))
                for _k, _v in obj.get("details").items()
            )
            if obj.get("details") is not None
            else None,
            "message": obj.get("message")
        })
        return _obj


