# coding: utf-8

"""
    College Football Data API

    Build college football applications, models, and analysis with game, team, player, recruiting, ranking, and advanced metrics data. Request an API key at CollegeFootballData.com.

    The version of the OpenAPI document: 5.27.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt

class PassingLocationProduction(BaseModel):
    """
    Production for analysis-eligible attempts in one location bucket.  # noqa: E501
    """
    attempts: StrictInt = Field(...)
    completions: StrictInt = Field(...)
    incompletions: StrictInt = Field(...)
    interceptions: StrictInt = Field(...)
    completion_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="completionRate")
    air_yards_attempts_available: StrictInt = Field(default=..., alias="airYardsAttemptsAvailable", description="Number of attempts with non-null air yards, including zero-yard values.")
    total_air_yards: Optional[StrictInt] = Field(default=..., alias="totalAirYards")
    average_depth_of_target: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="averageDepthOfTarget")
    total_yards_attempts_available: StrictInt = Field(default=..., alias="totalYardsAttemptsAvailable", description="Number of attempts with non-null total yards, including zero-yard incompletions and interceptions.")
    total_yards: Optional[StrictInt] = Field(default=..., alias="totalYards")
    yards_after_catch_attempts_available: StrictInt = Field(default=..., alias="yardsAfterCatchAttemptsAvailable", description="Number of completed attempts with valid total yards and air yards to calculate yards after catch, including zero-yard values.")
    total_yards_after_catch: Optional[StrictInt] = Field(default=..., alias="totalYardsAfterCatch")
    average_yards_after_catch: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="averageYardsAfterCatch")
    success_rate: Union[StrictFloat, StrictInt] = Field(default=..., alias="successRate", description="Successful eligible attempts / all eligible attempts; zero if empty.")
    ppa: Union[StrictFloat, StrictInt] = Field(default=..., description="Average available PPA on eligible attempts; zero if unavailable.")
    total_ppa: Union[StrictFloat, StrictInt] = Field(default=..., alias="totalPpa", description="Sum of available PPA on eligible attempts; zero if unavailable.")
    explosiveness: Union[StrictFloat, StrictInt] = Field(default=..., description="Average available PPA on successful eligible attempts; zero if unavailable.")
    ppa_attempts_available: StrictInt = Field(default=..., alias="ppaAttemptsAvailable", description="Eligible attempts with non-null PPA, including zero and negative values.")
    success_attempts_available: StrictInt = Field(default=..., alias="successAttemptsAvailable", description="Eligible attempts with non-null success. Missing success remains in the success-rate denominator but does not count as successful.")
    successful_attempts: StrictInt = Field(default=..., alias="successfulAttempts", description="Eligible attempts with stored success equal to true.")
    successful_ppa_attempts_available: StrictInt = Field(default=..., alias="successfulPpaAttemptsAvailable", description="Successful eligible attempts with non-null PPA; explosiveness denominator.")
    yards_per_attempt: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="yardsPerAttempt", description="Total yards / attempts with total yards available; null if unavailable.")
    air_yards_per_attempt: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="airYardsPerAttempt", description="Total air yards / attempts with air yards available; null if unavailable. Equivalent to averageDepthOfTarget. Yardage averages use one decimal.")
    __properties = ["attempts", "completions", "incompletions", "interceptions", "completionRate", "airYardsAttemptsAvailable", "totalAirYards", "averageDepthOfTarget", "totalYardsAttemptsAvailable", "totalYards", "yardsAfterCatchAttemptsAvailable", "totalYardsAfterCatch", "averageYardsAfterCatch", "successRate", "ppa", "totalPpa", "explosiveness", "ppaAttemptsAvailable", "successAttemptsAvailable", "successfulAttempts", "successfulPpaAttemptsAvailable", "yardsPerAttempt", "airYardsPerAttempt"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PassingLocationProduction:
        """Create an instance of PassingLocationProduction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if completion_rate (nullable) is None
        # and __fields_set__ contains the field
        if self.completion_rate is None and "completion_rate" in self.__fields_set__:
            _dict['completionRate'] = None

        # set to None if total_air_yards (nullable) is None
        # and __fields_set__ contains the field
        if self.total_air_yards is None and "total_air_yards" in self.__fields_set__:
            _dict['totalAirYards'] = None

        # set to None if average_depth_of_target (nullable) is None
        # and __fields_set__ contains the field
        if self.average_depth_of_target is None and "average_depth_of_target" in self.__fields_set__:
            _dict['averageDepthOfTarget'] = None

        # set to None if total_yards (nullable) is None
        # and __fields_set__ contains the field
        if self.total_yards is None and "total_yards" in self.__fields_set__:
            _dict['totalYards'] = None

        # set to None if total_yards_after_catch (nullable) is None
        # and __fields_set__ contains the field
        if self.total_yards_after_catch is None and "total_yards_after_catch" in self.__fields_set__:
            _dict['totalYardsAfterCatch'] = None

        # set to None if average_yards_after_catch (nullable) is None
        # and __fields_set__ contains the field
        if self.average_yards_after_catch is None and "average_yards_after_catch" in self.__fields_set__:
            _dict['averageYardsAfterCatch'] = None

        # set to None if yards_per_attempt (nullable) is None
        # and __fields_set__ contains the field
        if self.yards_per_attempt is None and "yards_per_attempt" in self.__fields_set__:
            _dict['yardsPerAttempt'] = None

        # set to None if air_yards_per_attempt (nullable) is None
        # and __fields_set__ contains the field
        if self.air_yards_per_attempt is None and "air_yards_per_attempt" in self.__fields_set__:
            _dict['airYardsPerAttempt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PassingLocationProduction:
        """Create an instance of PassingLocationProduction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PassingLocationProduction.parse_obj(obj)

        _obj = PassingLocationProduction.parse_obj({
            "attempts": obj.get("attempts"),
            "completions": obj.get("completions"),
            "incompletions": obj.get("incompletions"),
            "interceptions": obj.get("interceptions"),
            "completion_rate": obj.get("completionRate"),
            "air_yards_attempts_available": obj.get("airYardsAttemptsAvailable"),
            "total_air_yards": obj.get("totalAirYards"),
            "average_depth_of_target": obj.get("averageDepthOfTarget"),
            "total_yards_attempts_available": obj.get("totalYardsAttemptsAvailable"),
            "total_yards": obj.get("totalYards"),
            "yards_after_catch_attempts_available": obj.get("yardsAfterCatchAttemptsAvailable"),
            "total_yards_after_catch": obj.get("totalYardsAfterCatch"),
            "average_yards_after_catch": obj.get("averageYardsAfterCatch"),
            "success_rate": obj.get("successRate"),
            "ppa": obj.get("ppa"),
            "total_ppa": obj.get("totalPpa"),
            "explosiveness": obj.get("explosiveness"),
            "ppa_attempts_available": obj.get("ppaAttemptsAvailable"),
            "success_attempts_available": obj.get("successAttemptsAvailable"),
            "successful_attempts": obj.get("successfulAttempts"),
            "successful_ppa_attempts_available": obj.get("successfulPpaAttemptsAvailable"),
            "yards_per_attempt": obj.get("yardsPerAttempt"),
            "air_yards_per_attempt": obj.get("airYardsPerAttempt")
        })
        return _obj


