# coding: utf-8

"""
    College Football Data API

    Build college football applications, models, and analysis with game, team, player, recruiting, ranking, and advanced metrics data. Request an API key at CollegeFootballData.com.

    The version of the OpenAPI document: 5.27.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr
from cfbd.models.player_rushing_season_directions import PlayerRushingSeasonDirections

class PlayerRushingSeason(BaseModel):
    """
    PlayerRushingSeason
    """
    attempts: StrictInt = Field(...)
    rushing_yards_available: StrictInt = Field(default=..., alias="rushingYardsAvailable")
    total_rushing_yards: Optional[StrictInt] = Field(default=..., alias="totalRushingYards")
    yards_per_carry: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="yardsPerCarry")
    individual_attempts: StrictInt = Field(default=..., alias="individualAttempts")
    unattributed_attempts: StrictInt = Field(default=..., alias="unattributedAttempts")
    sacks: StrictInt = Field(...)
    kneels: StrictInt = Field(...)
    team_rushes: StrictInt = Field(default=..., alias="teamRushes")
    multi_carrier_attempts: StrictInt = Field(default=..., alias="multiCarrierAttempts")
    direction_eligible_attempts: StrictInt = Field(default=..., alias="directionEligibleAttempts")
    direction_available_attempts: StrictInt = Field(default=..., alias="directionAvailableAttempts")
    success_rate: Union[StrictFloat, StrictInt] = Field(default=..., alias="successRate")
    ppa: Union[StrictFloat, StrictInt] = Field(...)
    total_ppa: Union[StrictFloat, StrictInt] = Field(default=..., alias="totalPpa")
    line_yards: Union[StrictFloat, StrictInt] = Field(default=..., alias="lineYards")
    line_yards_total: Union[StrictFloat, StrictInt] = Field(default=..., alias="lineYardsTotal")
    second_level_yards: Union[StrictFloat, StrictInt] = Field(default=..., alias="secondLevelYards")
    second_level_yards_total: Union[StrictFloat, StrictInt] = Field(default=..., alias="secondLevelYardsTotal")
    open_field_yards: Union[StrictFloat, StrictInt] = Field(default=..., alias="openFieldYards")
    open_field_yards_total: Union[StrictFloat, StrictInt] = Field(default=..., alias="openFieldYardsTotal")
    stuff_rate: Union[StrictFloat, StrictInt] = Field(default=..., alias="stuffRate")
    power_success: Union[StrictFloat, StrictInt] = Field(default=..., alias="powerSuccess")
    explosiveness: Union[StrictFloat, StrictInt] = Field(...)
    directions: PlayerRushingSeasonDirections = Field(...)
    season: StrictInt = Field(...)
    player_id: StrictStr = Field(default=..., alias="playerId")
    player: StrictStr = Field(...)
    team: StrictStr = Field(...)
    conference: Optional[StrictStr] = Field(...)
    __properties = ["attempts", "rushingYardsAvailable", "totalRushingYards", "yardsPerCarry", "individualAttempts", "unattributedAttempts", "sacks", "kneels", "teamRushes", "multiCarrierAttempts", "directionEligibleAttempts", "directionAvailableAttempts", "successRate", "ppa", "totalPpa", "lineYards", "lineYardsTotal", "secondLevelYards", "secondLevelYardsTotal", "openFieldYards", "openFieldYardsTotal", "stuffRate", "powerSuccess", "explosiveness", "directions", "season", "playerId", "player", "team", "conference"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PlayerRushingSeason:
        """Create an instance of PlayerRushingSeason from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of directions
        if self.directions:
            _dict['directions'] = self.directions.to_dict()
        # set to None if total_rushing_yards (nullable) is None
        # and __fields_set__ contains the field
        if self.total_rushing_yards is None and "total_rushing_yards" in self.__fields_set__:
            _dict['totalRushingYards'] = None

        # set to None if yards_per_carry (nullable) is None
        # and __fields_set__ contains the field
        if self.yards_per_carry is None and "yards_per_carry" in self.__fields_set__:
            _dict['yardsPerCarry'] = None

        # set to None if conference (nullable) is None
        # and __fields_set__ contains the field
        if self.conference is None and "conference" in self.__fields_set__:
            _dict['conference'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PlayerRushingSeason:
        """Create an instance of PlayerRushingSeason from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PlayerRushingSeason.parse_obj(obj)

        _obj = PlayerRushingSeason.parse_obj({
            "attempts": obj.get("attempts"),
            "rushing_yards_available": obj.get("rushingYardsAvailable"),
            "total_rushing_yards": obj.get("totalRushingYards"),
            "yards_per_carry": obj.get("yardsPerCarry"),
            "individual_attempts": obj.get("individualAttempts"),
            "unattributed_attempts": obj.get("unattributedAttempts"),
            "sacks": obj.get("sacks"),
            "kneels": obj.get("kneels"),
            "team_rushes": obj.get("teamRushes"),
            "multi_carrier_attempts": obj.get("multiCarrierAttempts"),
            "direction_eligible_attempts": obj.get("directionEligibleAttempts"),
            "direction_available_attempts": obj.get("directionAvailableAttempts"),
            "success_rate": obj.get("successRate"),
            "ppa": obj.get("ppa"),
            "total_ppa": obj.get("totalPpa"),
            "line_yards": obj.get("lineYards"),
            "line_yards_total": obj.get("lineYardsTotal"),
            "second_level_yards": obj.get("secondLevelYards"),
            "second_level_yards_total": obj.get("secondLevelYardsTotal"),
            "open_field_yards": obj.get("openFieldYards"),
            "open_field_yards_total": obj.get("openFieldYardsTotal"),
            "stuff_rate": obj.get("stuffRate"),
            "power_success": obj.get("powerSuccess"),
            "explosiveness": obj.get("explosiveness"),
            "directions": PlayerRushingSeasonDirections.from_dict(obj.get("directions")) if obj.get("directions") is not None else None,
            "season": obj.get("season"),
            "player_id": obj.get("playerId"),
            "player": obj.get("player"),
            "team": obj.get("team"),
            "conference": obj.get("conference")
        })
        return _obj


