# coding: utf-8

"""
    College Football Data API

    This is an API for query various college football datasets and analytics. API keys can be acquired from the CollegeFootballData.com website.

    The version of the OpenAPI document: 5.19.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist
from cfbd.models.playoff_advancement import PlayoffAdvancement
from cfbd.models.playoff_linked_game import PlayoffLinkedGame
from cfbd.models.playoff_matchup_slot import PlayoffMatchupSlot
from cfbd.models.playoff_round import PlayoffRound

class PlayoffMatchup(BaseModel):
    """
    PlayoffMatchup
    """
    id: StrictInt = Field(...)
    bracket_slot: StrictStr = Field(default=..., alias="bracketSlot")
    round: PlayoffRound = Field(...)
    round_name: StrictStr = Field(default=..., alias="roundName")
    round_order: StrictInt = Field(default=..., alias="roundOrder")
    matchup_order: StrictInt = Field(default=..., alias="matchupOrder")
    start_date: Optional[datetime] = Field(default=..., alias="startDate")
    bowl_name: Optional[StrictStr] = Field(default=..., alias="bowlName")
    slots: conlist(PlayoffMatchupSlot) = Field(...)
    game: Optional[PlayoffLinkedGame] = Field(...)
    advances_to: Optional[PlayoffAdvancement] = Field(default=..., alias="advancesTo")
    __properties = ["id", "bracketSlot", "round", "roundName", "roundOrder", "matchupOrder", "startDate", "bowlName", "slots", "game", "advancesTo"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PlayoffMatchup:
        """Create an instance of PlayoffMatchup from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in slots (list)
        _items = []
        if self.slots:
            for _item in self.slots:
                if _item:
                    _items.append(_item.to_dict())
            _dict['slots'] = _items
        # override the default output from pydantic by calling `to_dict()` of game
        if self.game:
            _dict['game'] = self.game.to_dict()
        # override the default output from pydantic by calling `to_dict()` of advances_to
        if self.advances_to:
            _dict['advancesTo'] = self.advances_to.to_dict()
        # set to None if start_date (nullable) is None
        # and __fields_set__ contains the field
        if self.start_date is None and "start_date" in self.__fields_set__:
            _dict['startDate'] = None

        # set to None if bowl_name (nullable) is None
        # and __fields_set__ contains the field
        if self.bowl_name is None and "bowl_name" in self.__fields_set__:
            _dict['bowlName'] = None

        # set to None if game (nullable) is None
        # and __fields_set__ contains the field
        if self.game is None and "game" in self.__fields_set__:
            _dict['game'] = None

        # set to None if advances_to (nullable) is None
        # and __fields_set__ contains the field
        if self.advances_to is None and "advances_to" in self.__fields_set__:
            _dict['advancesTo'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PlayoffMatchup:
        """Create an instance of PlayoffMatchup from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PlayoffMatchup.parse_obj(obj)

        _obj = PlayoffMatchup.parse_obj({
            "id": obj.get("id"),
            "bracket_slot": obj.get("bracketSlot"),
            "round": obj.get("round"),
            "round_name": obj.get("roundName"),
            "round_order": obj.get("roundOrder"),
            "matchup_order": obj.get("matchupOrder"),
            "start_date": obj.get("startDate"),
            "bowl_name": obj.get("bowlName"),
            "slots": [PlayoffMatchupSlot.from_dict(_item) for _item in obj.get("slots")] if obj.get("slots") is not None else None,
            "game": PlayoffLinkedGame.from_dict(obj.get("game")) if obj.get("game") is not None else None,
            "advances_to": PlayoffAdvancement.from_dict(obj.get("advancesTo")) if obj.get("advancesTo") is not None else None
        })
        return _obj


