# coding: utf-8

"""
    College Football Data API

    This is an API for query various college football datasets and analytics. API keys can be acquired from the CollegeFootballData.com website.

    The version of the OpenAPI document: 5.18.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt

class PlayerSuccessRateSplit(BaseModel):
    """
    PlayerSuccessRateSplit
    """
    plays: StrictInt = Field(...)
    successes: StrictInt = Field(...)
    success_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="successRate")
    __properties = ["plays", "successes", "successRate"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PlayerSuccessRateSplit:
        """Create an instance of PlayerSuccessRateSplit from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if success_rate (nullable) is None
        # and __fields_set__ contains the field
        if self.success_rate is None and "success_rate" in self.__fields_set__:
            _dict['successRate'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PlayerSuccessRateSplit:
        """Create an instance of PlayerSuccessRateSplit from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PlayerSuccessRateSplit.parse_obj(obj)

        _obj = PlayerSuccessRateSplit.parse_obj({
            "plays": obj.get("plays"),
            "successes": obj.get("successes"),
            "success_rate": obj.get("successRate")
        })
        return _obj


