# coding: utf-8

"""
    College Football Data API

    This is an API for query various college football datasets and analytics. API keys can be acquired from the CollegeFootballData.com website.

    The version of the OpenAPI document: 5.18.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt
from cfbd.models.playoff_matchup_slot_source import PlayoffMatchupSlotSource
from cfbd.models.playoff_team import PlayoffTeam

class PlayoffMatchupSlot(BaseModel):
    """
    PlayoffMatchupSlot
    """
    position: StrictInt = Field(...)
    seed: Optional[StrictInt] = Field(...)
    participant: Optional[PlayoffTeam] = Field(...)
    source: Optional[PlayoffMatchupSlotSource] = Field(...)
    __properties = ["position", "seed", "participant", "source"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PlayoffMatchupSlot:
        """Create an instance of PlayoffMatchupSlot from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of participant
        if self.participant:
            _dict['participant'] = self.participant.to_dict()
        # override the default output from pydantic by calling `to_dict()` of source
        if self.source:
            _dict['source'] = self.source.to_dict()
        # set to None if seed (nullable) is None
        # and __fields_set__ contains the field
        if self.seed is None and "seed" in self.__fields_set__:
            _dict['seed'] = None

        # set to None if participant (nullable) is None
        # and __fields_set__ contains the field
        if self.participant is None and "participant" in self.__fields_set__:
            _dict['participant'] = None

        # set to None if source (nullable) is None
        # and __fields_set__ contains the field
        if self.source is None and "source" in self.__fields_set__:
            _dict['source'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PlayoffMatchupSlot:
        """Create an instance of PlayoffMatchupSlot from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PlayoffMatchupSlot.parse_obj(obj)

        _obj = PlayoffMatchupSlot.parse_obj({
            "position": obj.get("position"),
            "seed": obj.get("seed"),
            "participant": PlayoffTeam.from_dict(obj.get("participant")) if obj.get("participant") is not None else None,
            "source": PlayoffMatchupSlotSource.from_dict(obj.get("source")) if obj.get("source") is not None else None
        })
        return _obj


