# coding: utf-8

"""
    College Football Data API

    Build college football applications, models, and analysis with game, team, player, recruiting, ranking, and advanced metrics data. Request an API key at CollegeFootballData.com.

    The version of the OpenAPI document: 5.31.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field
from cfbd.models.team_season_ranked_rating import TeamSeasonRankedRating

class TeamSeasonOverviewRatingsSp(BaseModel):
    """
    TeamSeasonOverviewRatingsSp
    """
    special_teams: TeamSeasonRankedRating = Field(default=..., alias="specialTeams")
    defense: TeamSeasonRankedRating = Field(...)
    offense: TeamSeasonRankedRating = Field(...)
    overall: TeamSeasonRankedRating = Field(...)
    __properties = ["specialTeams", "defense", "offense", "overall"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TeamSeasonOverviewRatingsSp:
        """Create an instance of TeamSeasonOverviewRatingsSp from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of special_teams
        if self.special_teams:
            _dict['specialTeams'] = self.special_teams.to_dict()
        # override the default output from pydantic by calling `to_dict()` of defense
        if self.defense:
            _dict['defense'] = self.defense.to_dict()
        # override the default output from pydantic by calling `to_dict()` of offense
        if self.offense:
            _dict['offense'] = self.offense.to_dict()
        # override the default output from pydantic by calling `to_dict()` of overall
        if self.overall:
            _dict['overall'] = self.overall.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TeamSeasonOverviewRatingsSp:
        """Create an instance of TeamSeasonOverviewRatingsSp from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TeamSeasonOverviewRatingsSp.parse_obj(obj)

        _obj = TeamSeasonOverviewRatingsSp.parse_obj({
            "special_teams": TeamSeasonRankedRating.from_dict(obj.get("specialTeams")) if obj.get("specialTeams") is not None else None,
            "defense": TeamSeasonRankedRating.from_dict(obj.get("defense")) if obj.get("defense") is not None else None,
            "offense": TeamSeasonRankedRating.from_dict(obj.get("offense")) if obj.get("offense") is not None else None,
            "overall": TeamSeasonRankedRating.from_dict(obj.get("overall")) if obj.get("overall") is not None else None
        })
        return _obj


