# coding: utf-8

"""
    College Football Data API

    This is an API for query various college football datasets and analytics. API keys can be acquired from the CollegeFootballData.com website.

    The version of the OpenAPI document: 5.13.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr

class TeamATS(BaseModel):
    """
    TeamATS
    """
    year: StrictInt = Field(...)
    team_id: StrictInt = Field(default=..., alias="teamId")
    team: StrictStr = Field(...)
    conference: Optional[StrictStr] = Field(...)
    games: StrictInt = Field(...)
    ats_wins: StrictInt = Field(default=..., alias="atsWins")
    ats_losses: StrictInt = Field(default=..., alias="atsLosses")
    ats_pushes: StrictInt = Field(default=..., alias="atsPushes")
    avg_cover_margin: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="avgCoverMargin")
    __properties = ["year", "teamId", "team", "conference", "games", "atsWins", "atsLosses", "atsPushes", "avgCoverMargin"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TeamATS:
        """Create an instance of TeamATS from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if conference (nullable) is None
        # and __fields_set__ contains the field
        if self.conference is None and "conference" in self.__fields_set__:
            _dict['conference'] = None

        # set to None if avg_cover_margin (nullable) is None
        # and __fields_set__ contains the field
        if self.avg_cover_margin is None and "avg_cover_margin" in self.__fields_set__:
            _dict['avgCoverMargin'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TeamATS:
        """Create an instance of TeamATS from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TeamATS.parse_obj(obj)

        _obj = TeamATS.parse_obj({
            "year": obj.get("year"),
            "team_id": obj.get("teamId"),
            "team": obj.get("team"),
            "conference": obj.get("conference"),
            "games": obj.get("games"),
            "ats_wins": obj.get("atsWins"),
            "ats_losses": obj.get("atsLosses"),
            "ats_pushes": obj.get("atsPushes"),
            "avg_cover_margin": obj.get("avgCoverMargin")
        })
        return _obj


