# coding: utf-8

"""
    College Football Data API

    Build college football applications, models, and analysis with game, team, player, recruiting, ranking, and advanced metrics data. Request an API key at CollegeFootballData.com.

    The version of the OpenAPI document: 5.24.1
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr
from cfbd.models.conference_classification import ConferenceClassification

class TeamConferenceAffiliation(BaseModel):
    """
    TeamConferenceAffiliation
    """
    team_id: StrictInt = Field(default=..., alias="teamId")
    team: StrictStr = Field(...)
    conference_id: StrictInt = Field(default=..., alias="conferenceId")
    conference: StrictStr = Field(...)
    conference_abbreviation: Optional[StrictStr] = Field(default=..., alias="conferenceAbbreviation")
    classification: Optional[ConferenceClassification] = Field(...)
    conference_division: Optional[StrictStr] = Field(default=..., alias="conferenceDivision")
    start_year: StrictInt = Field(default=..., alias="startYear")
    end_year: Optional[StrictInt] = Field(default=..., alias="endYear")
    __properties = ["teamId", "team", "conferenceId", "conference", "conferenceAbbreviation", "classification", "conferenceDivision", "startYear", "endYear"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TeamConferenceAffiliation:
        """Create an instance of TeamConferenceAffiliation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if conference_abbreviation (nullable) is None
        # and __fields_set__ contains the field
        if self.conference_abbreviation is None and "conference_abbreviation" in self.__fields_set__:
            _dict['conferenceAbbreviation'] = None

        # set to None if classification (nullable) is None
        # and __fields_set__ contains the field
        if self.classification is None and "classification" in self.__fields_set__:
            _dict['classification'] = None

        # set to None if conference_division (nullable) is None
        # and __fields_set__ contains the field
        if self.conference_division is None and "conference_division" in self.__fields_set__:
            _dict['conferenceDivision'] = None

        # set to None if end_year (nullable) is None
        # and __fields_set__ contains the field
        if self.end_year is None and "end_year" in self.__fields_set__:
            _dict['endYear'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TeamConferenceAffiliation:
        """Create an instance of TeamConferenceAffiliation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TeamConferenceAffiliation.parse_obj(obj)

        _obj = TeamConferenceAffiliation.parse_obj({
            "team_id": obj.get("teamId"),
            "team": obj.get("team"),
            "conference_id": obj.get("conferenceId"),
            "conference": obj.get("conference"),
            "conference_abbreviation": obj.get("conferenceAbbreviation"),
            "classification": obj.get("classification"),
            "conference_division": obj.get("conferenceDivision"),
            "start_year": obj.get("startYear"),
            "end_year": obj.get("endYear")
        })
        return _obj


