# coding: utf-8

"""
    College Football Data API

    Build college football applications, models, and analysis with game, team, player, recruiting, ranking, and advanced metrics data. Request an API key at CollegeFootballData.com.

    The version of the OpenAPI document: 5.30.1
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr
from cfbd.models.team_passing_season import TeamPassingSeason
from cfbd.models.team_rushing_season import TeamRushingSeason
from cfbd.models.team_season_advanced_stats import TeamSeasonAdvancedStats
from cfbd.models.team_season_overview_players import TeamSeasonOverviewPlayers
from cfbd.models.team_season_overview_ratings import TeamSeasonOverviewRatings
from cfbd.models.team_season_overview_record import TeamSeasonOverviewRecord

class TeamSeasonOverview(BaseModel):
    """
    TeamSeasonOverview
    """
    advanced: TeamSeasonAdvancedStats = Field(...)
    players: TeamSeasonOverviewPlayers = Field(...)
    passing: Optional[TeamPassingSeason] = Field(...)
    rushing: Optional[TeamRushingSeason] = Field(...)
    record: TeamSeasonOverviewRecord = Field(...)
    ratings: TeamSeasonOverviewRatings = Field(...)
    season: StrictInt = Field(...)
    team_id: StrictInt = Field(default=..., alias="teamId")
    team: StrictStr = Field(...)
    __properties = ["advanced", "players", "passing", "rushing", "record", "ratings", "season", "teamId", "team"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TeamSeasonOverview:
        """Create an instance of TeamSeasonOverview from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of advanced
        if self.advanced:
            _dict['advanced'] = self.advanced.to_dict()
        # override the default output from pydantic by calling `to_dict()` of players
        if self.players:
            _dict['players'] = self.players.to_dict()
        # override the default output from pydantic by calling `to_dict()` of passing
        if self.passing:
            _dict['passing'] = self.passing.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rushing
        if self.rushing:
            _dict['rushing'] = self.rushing.to_dict()
        # override the default output from pydantic by calling `to_dict()` of record
        if self.record:
            _dict['record'] = self.record.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ratings
        if self.ratings:
            _dict['ratings'] = self.ratings.to_dict()
        # set to None if passing (nullable) is None
        # and __fields_set__ contains the field
        if self.passing is None and "passing" in self.__fields_set__:
            _dict['passing'] = None

        # set to None if rushing (nullable) is None
        # and __fields_set__ contains the field
        if self.rushing is None and "rushing" in self.__fields_set__:
            _dict['rushing'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TeamSeasonOverview:
        """Create an instance of TeamSeasonOverview from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TeamSeasonOverview.parse_obj(obj)

        _obj = TeamSeasonOverview.parse_obj({
            "advanced": TeamSeasonAdvancedStats.from_dict(obj.get("advanced")) if obj.get("advanced") is not None else None,
            "players": TeamSeasonOverviewPlayers.from_dict(obj.get("players")) if obj.get("players") is not None else None,
            "passing": TeamPassingSeason.from_dict(obj.get("passing")) if obj.get("passing") is not None else None,
            "rushing": TeamRushingSeason.from_dict(obj.get("rushing")) if obj.get("rushing") is not None else None,
            "record": TeamSeasonOverviewRecord.from_dict(obj.get("record")) if obj.get("record") is not None else None,
            "ratings": TeamSeasonOverviewRatings.from_dict(obj.get("ratings")) if obj.get("ratings") is not None else None,
            "season": obj.get("season"),
            "team_id": obj.get("teamId"),
            "team": obj.get("team")
        })
        return _obj


