# coding: utf-8

"""
    College Football Data API

    This is an API for query various college football datasets and analytics. API keys can be acquired from the CollegeFootballData.com website.

    The version of the OpenAPI document: 5.20.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, conlist
from cfbd.models.user_usage_api import UserUsageApi
from cfbd.models.user_usage_endpoint import UserUsageEndpoint
from cfbd.models.user_usage_recent_request import UserUsageRecentRequest
from cfbd.models.user_usage_totals import UserUsageTotals
from cfbd.models.user_usage_window import UserUsageWindow

class UserUsage(BaseModel):
    """
    UserUsage
    """
    window: UserUsageWindow = Field(...)
    api: UserUsageApi = Field(...)
    totals: UserUsageTotals = Field(...)
    top_endpoints: conlist(UserUsageEndpoint) = Field(default=..., alias="topEndpoints")
    recent_requests: conlist(UserUsageRecentRequest) = Field(default=..., alias="recentRequests")
    __properties = ["window", "api", "totals", "topEndpoints", "recentRequests"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UserUsage:
        """Create an instance of UserUsage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of window
        if self.window:
            _dict['window'] = self.window.to_dict()
        # override the default output from pydantic by calling `to_dict()` of totals
        if self.totals:
            _dict['totals'] = self.totals.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in top_endpoints (list)
        _items = []
        if self.top_endpoints:
            for _item in self.top_endpoints:
                if _item:
                    _items.append(_item.to_dict())
            _dict['topEndpoints'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in recent_requests (list)
        _items = []
        if self.recent_requests:
            for _item in self.recent_requests:
                if _item:
                    _items.append(_item.to_dict())
            _dict['recentRequests'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UserUsage:
        """Create an instance of UserUsage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UserUsage.parse_obj(obj)

        _obj = UserUsage.parse_obj({
            "window": UserUsageWindow.from_dict(obj.get("window")) if obj.get("window") is not None else None,
            "api": obj.get("api"),
            "totals": UserUsageTotals.from_dict(obj.get("totals")) if obj.get("totals") is not None else None,
            "top_endpoints": [UserUsageEndpoint.from_dict(_item) for _item in obj.get("topEndpoints")] if obj.get("topEndpoints") is not None else None,
            "recent_requests": [UserUsageRecentRequest.from_dict(_item) for _item in obj.get("recentRequests")] if obj.get("recentRequests") is not None else None
        })
        return _obj


